sst/sst

lerna.json
packages/cli/scripts/start.js
packages/cli/test/jest/lib/mystack.js
packages/cli/test/lambda-override-eslintrc/lib/index.js
packages/cli/test/start-base/lib/index.js
packages/cli/test/start-base/sst.json
packages/cli/test/start-base/start-base.test.js
packages/cli/test/start-no-src-path/lib/index.js
packages/cli/test/start-no-src-path/sst.json
packages/cli/test/start-no-src-path/start-no-src-path.test.js
packages/resources/lambda/stub/index.js
packages/resources/src/App.ts
packages/resources/src/Function.ts
packages/resources/src/util/builder.ts

Remove entry from sst.Function construct

---

packages/resources/src/Function.ts
www/docs/packages/resources.md

Closes https://github.com/serverless-stack/serverless-stack/issues/44 & https://github.com/serverless-stack/serverless-stack/issues/43

Updating sst.Functions docs

---

packages/cli/scripts/util/cdkHelpers.js

Debug logs not flushed to file on process.exit

---

packages/cli/scripts/util/cdkHelpers.js
packages/resources/src/App.ts

Fixing paths to detect TypeScript bin in Windows

---

packages/cli/scripts/util/cdkHelpers.js

Ignoring node_modules for ESLint CDK code

---

packages/cli/scripts/start.js
packages/cli/scripts/util/cdkHelpers.js
packages/resources/.npmignore
packages/resources/src/App.ts

Related to https://github.com/serverless-stack/serverless-stack/pull/68

Set the srcpath for lambda eslint process to handle plugin resolution

---

packages/create-serverless-stack/templates/javascript/README.template.md
packages/create-serverless-stack/templates/typescript/README.template.md

Updating README in templates

---

packages/cli/scripts/start.js
packages/cli/scripts/util/cdkHelpers.js
packages/resources/src/util/builder.ts

Set esbuild target to "es2015"

---

packages/resources/src/Auth.ts
packages/resources/test/Auth.test.ts

Add Auth0 support for `sst.Auth`

---

packages/resources/package.json
packages/resources/src/util/permission.ts
packages/resources/test/Function.test.ts

Attach table and bucket permissions grants access to /* sub-resource

---

packages/resources/package.json
packages/resources/src/Api.ts
packages/resources/test/Api.test.ts
www/docs/constructs/api.md

Support custom domain for Api construct

---

packages/resources/src/util/permission.ts
packages/resources/test/Function.test.ts

Closes #139
@fwang Review the changes

Fix attachPermission instanceof error

---

packages/cli/assets/lambda-invoke/bootstrap.js
packages/cli/scripts/start.js

Support context.getRemainingTimeInMillis() in live development

---

packages/cli/scripts/start.js
packages/cli/test/lambda-override-tsconfig/src/tsconfig.json
packages/cli/test/lambda-override-tsconfig/tsconfig.json
packages/cli/test/start-base/lib/index.js
packages/resources/src/App.ts
www/docs/constructs/function.md

Fixing tsc error if no tsconfig.json is found

---

packages/resources/src/Api.ts
packages/resources/test/Api.test.ts
www/docs/constructs/Api.md

Support payload format version in Api construct

---

packages/resources/src/Api.ts
packages/resources/test/Api.test.ts
www/docs/constructs/Api.md
www/docs/constructs/Topic.md

Support all CDK Http Api options

---

packages/resources/src/Api.ts

Handle Api.getFunction for non-existent route keys

---

packages/resources/src/Api.ts
packages/resources/src/Auth.ts
packages/resources/src/Queue.ts
packages/resources/src/Table.ts
packages/resources/src/Topic.ts

Closes https://github.com/serverless-stack/serverless-stack/issues/226

Fix typescript error when using imported constructs

---

packages/resources/src/Stack.ts

Add 'stage' property to Stack construct

---

packages/cli/scripts/start.js

Add IS_LOCAL environment variable when runing `sst start`

---

packages/create-serverless-stack/templates/typescript/src/lambda.ts

As per Slack - I think this gives a more informative method signature for those coming to the project who are new to using TypeScript with AWS lambda.

Improves TS template method signature

---

packages/cli/bin/scripts.js
packages/cli/scripts/deploy.js
packages/cli/scripts/start.js
www/docs/packages/cli.md

Support outputs file option for sst start

---

packages/cli/bin/scripts.js
www/docs/packages/cli.md

Adding more context to CLI options

---

packages/cli/scripts/remove.js
packages/core/index.js
packages/resources/src/Function.ts

Skip bundling Lambda function on remove command

---

www/docs/constructs/Api.md
www/docs/constructs/ApiGatewayV1Api.md
www/docs/constructs/AppSyncApi.md
www/docs/constructs/Auth.md
www/docs/constructs/Bucket.md
www/docs/constructs/Cron.md
www/docs/constructs/Function.md
www/docs/constructs/Queue.md
www/docs/constructs/Stack.md
www/docs/constructs/Table.md
www/docs/constructs/Topic.md

Fixing cdk imports in docs

---

www/docs/constructs/Api.md
www/docs/constructs/ApiGatewayV1Api.md
www/docs/constructs/ApolloApi.md
www/docs/constructs/AppSyncApi.md
www/docs/constructs/Auth.md
www/docs/constructs/Bucket.md
www/docs/constructs/Cron.md
www/docs/constructs/Function.md
www/docs/constructs/Queue.md
www/docs/constructs/Table.md
www/docs/constructs/Topic.md

Showing example with sst import in constructs

---

www/docs/constructs/Api.md
www/docs/constructs/WebSocketApi.md
www/docs/migrating-from-cdk.md

Reviewing the WebSocket API docs

---

packages/create-serverless-stack/templates/go/lib/%stack-name.PascalCased%.template.js
packages/create-serverless-stack/templates/javascript/lib/%stack-name.PascalCased%.template.js
packages/create-serverless-stack/templates/python/lib/%stack-name.PascalCased%.template.js
packages/create-serverless-stack/templates/typescript/lib/%stack-name.PascalCased%.template.ts

Updating templates to use api.url

---

packages/resources/src/Stack.ts
packages/resources/src/Topic.ts
packages/resources/test/Stack.test.ts
packages/resources/test/Topic.test.ts

Stack: validate stack output is not undefined

---

README.md
www/docs/constructs/Auth.md
www/docs/migrating-from-serverless-framework.md
www/docs/packages/resources.md

Editing auth triggers docs changes

---

www/docs/packages/cli.md

Editing docs with SST auto-rebuilding CDK code

---

www/docs/constructs/Api.md
www/docs/constructs/KinesisStream.md
www/docs/constructs/Table.md
www/docs/constructs/Topic.md
www/docs/live-lambda-development.md
www/docs/packages/resources.md
www/docs/working-locally.md

Fixes #376 
Fixes #382 
Fixes #386 
Fixes #387 
Fixes #358
Fixes #395

Fixes to the docs

---

packages/cli/scripts/deploy.js
packages/cli/scripts/remove.js
packages/core/index.js

sst deploy/remove: use exit code 1 if stacks failed to deploy or remove

---

packages/cli/bin/scripts.js
www/docs/packages/cli.md

Tweaking copy in docs and helper

---

packages/cli/assets/cdk-wrapper/run.js
packages/cli/assets/debug-stack/bin/index.js
packages/cli/assets/debug-stack/lib/DebugStack.js
packages/cli/scripts/remove.js
packages/cli/scripts/start.js
packages/cli/scripts/util/cdkHelpers.js
packages/cli/test/playground/lib/index.ts
packages/core/index.js
packages/resources/src/App.ts
packages/resources/src/DebugStack.ts
packages/resources/src/index.ts

sst start: expose the app and the stack constructs in the debug stack

---

www/docs/constructs/Api.md
www/docs/constructs/Bucket.md
www/docs/constructs/Table.md
www/docs/debugging-with-vscode.md
www/docs/live-lambda-development.md
www/docs/packages/cli.md

Closes #399, Closes #400, Closes #431, Closes #434

Editing docs for recent changes

---

packages/cli/test/playground/lib/api-stack.ts
packages/resources/src/ApiGatewayV1Api.ts
packages/resources/test/ApiGatewayV1Api.test.ts

ApiGatewayV1Api: create Deployment resource when the REST Api is imported

---

packages/cli/bin/scripts.js
packages/cli/scripts/util/cdkHelpers.js
packages/core/index.js
www/docs/packages/cli.md

CLI: Add `--role-arn` option to take a CloudFormation execution role

---

packages/cli/assets/debug-stack/bin/index.js
packages/cli/scripts/remove.js
packages/cli/scripts/start.js

sst start: .env variables not available when deploying debug stack

---

packages/resources/src/App.ts
packages/resources/src/Stack.ts
www/docs/constructs/App.md

App: add account property

---

packages/resources/src/Function.ts
packages/resources/src/util/nodeBuilder.ts
packages/resources/test/Function.test.ts
www/docs/constructs/Function.md

Function: add bundling command hooks

---

packages/resources/src/AppSyncApi.ts
packages/resources/test/AppSyncApi.test.ts

AppSyncApi: do not normalize resolver key cases

---

packages/cli/test/playground/lib/cron-stack.ts
packages/resources/src/Cron.ts
packages/resources/test/Cron.test.ts
www/docs/constructs/Cron.md

Cron: allow configuring event payload

---

packages/resources/assets/python/Dockerfile.custom
packages/resources/src/Function.ts
packages/resources/src/util/nodeBuilder.ts
packages/resources/src/util/python/bundling.ts
packages/resources/src/util/pythonBuilder.ts
www/docs/constructs/Function.md

Function: support custom install commands for Python runtime

---

packages/resources/src/Api.ts
packages/resources/src/ApiGatewayV1Api.ts
packages/resources/src/WebSocketApi.ts
packages/resources/test/Api.test.ts
packages/resources/test/ApiGatewayV1Api.test.ts
packages/resources/test/WebSocketApi.test.ts

Api: check for duplicated routes at build time

---

packages/resources/package.json
packages/resources/src/Bucket.ts
packages/resources/test/Bucket.test.ts
www/docs/constructs/Bucket.md

Bucket: support Queue and Topic notifications

---

www/docs/migrating-from-serverless-framework.md

Migration guide: add an example of hybrid multi-service Serverless Framework and SST app

---

packages/create-serverless-stack/templates/go/.env
packages/create-serverless-stack/templates/go/.template.gitignore
packages/create-serverless-stack/templates/javascript/.env
packages/create-serverless-stack/templates/javascript/.template.gitignore
packages/create-serverless-stack/templates/python/.env
packages/create-serverless-stack/templates/python/.template.gitignore
packages/create-serverless-stack/templates/typescript/.env
packages/create-serverless-stack/templates/typescript/.template.gitignore

Template: add .env to starter template

---

packages/resources/package.json
packages/resources/src/Function.ts
packages/resources/test/Function.test.ts
www/docs/constructs/Function.md

Function: support sharing layers across stacks

---

packages/cli/scripts/test.js
www/docs/environment-variables.md

sst test: support .env environment variables for running tests

---

packages/resources/src/StaticSite.ts
packages/resources/test/StaticSite.test.ts

StaticSite: allow extending the function for creating Route 53 records

---

packages/cli/assets/cdk-wrapper/run.js
packages/resources/src/App.ts

ReactStaticSite: display environment variables in sst deploy output

---

packages/cli/scripts/start.js
packages/cli/test/lambda-handler-relative/lambda-handler-relative.test.js
packages/cli/test/lambda-handler-relative/lambda.js
packages/cli/test/lambda-handler-relative/lib/index.js
packages/cli/test/lambda-handler-relative/package.json
packages/cli/test/lambda-handler-relative/sst.json

Fix for specifying handler with period in path

---

packages/resources/src/StaticSite.ts
packages/resources/test/StaticSite.test.ts

StaticSite: check path and buildOutput exist on build

---

packages/resources/src/Api.ts
packages/resources/test/Api.test.ts
www/docs/constructs/Api.md

Api: add support for HTTP proxy routes

---

www/docs/constructs/Api.md

The actual commit https://github.com/serverless-stack/serverless-stack/commit/90e171301c567d9c85c6a93fb6346d4752427320

Api: support $default catch-all route

---

packages/cli/test/playground/lib/apollo-api-stack.ts
packages/cli/test/playground/lib/index.ts
packages/resources/src/Api.ts
packages/resources/src/ApolloApi.ts
packages/resources/test/ApolloApi.test.ts

ApolloApi: create 1 Lambda handler for both GET and POST routes

---

README.md
packages/cli/test/playground/lib/eventbus-stack.ts
packages/cli/test/playground/lib/index.ts
packages/resources/src/EventBus.ts
packages/resources/src/index.ts
packages/resources/src/util/permission.ts
packages/resources/test/EventBus.test.ts
packages/resources/test/Function.test.ts
www/docs/constructs/EventBus.md
www/docs/constructs/Function.md
www/sidebars.js

EventBus: add high level construct for AWS EventBridge

---

packages/resources/src/ReactStaticSite.ts
packages/resources/src/StaticSite.ts
packages/resources/test/StaticSite.test.ts
www/docs/constructs/ReactStaticSite.md
www/docs/constructs/StaticSite.md

Support environment property in StaticSite

---

packages/resources/src/Function.ts
packages/resources/test/Function.test.ts

Support disabling local development feature

---

packages/resources/src/StaticSite.ts
packages/resources/test/StaticSite.test.ts

Refactored a bit to remove nesting as well

Fix static site looking for build directory when skipping build

---

packages/resources/src/ApolloApi.ts
packages/resources/test/ApolloApi.test.ts
www/docs/constructs/ApolloApi.md

ApolloApi: add serverFunction property

---

.github/workflows/ci.yml

Deprecate Node.js 10

---

packages/core/src/util/environment.ts

Fix: dotenv does not accept false as valid value to turn off debugging

---

packages/resources/src/Function.ts
packages/resources/test/Function.test.ts

Function: remove trailing slash from srcPath

---

packages/cli/package.json
packages/cli/scripts/start.js
packages/cli/scripts/util/LambdaWatcherState.js
packages/cli/scripts/util/cdkHelpers.js
packages/resources/assets/nodejs/esbuild.js
packages/resources/package.json
packages/resources/src/util/nodeBuilder.ts
yarn.lock

Update esbuild to 0.12.17

---

packages/cli/bin/scripts.js
www/docs/packages/cli.md

Tweaking update command copy

---

packages/cli/bin/scripts.js
packages/cli/test/update/update.test.js
packages/core/src/update/update.ts

CLI: Hide update command packager output behind verbose flag

---

packages/cli/lib/object.js
packages/cli/scripts/util/bootstrap.js

 sst start: handler function returning function crashes

---

packages/cli/scripts/start.js

sst start: print error object with full depth

---

packages/cli/bin/scripts.js
packages/cli/test/add-cdk/add-cdk.test.js
packages/core/src/index.js
packages/core/src/packager/index.ts
packages/core/src/packager/packager.ts
packages/core/src/update/update.ts

CLI: Scan recursively to figure out if project is using yarn

---

packages/core/src/index.js

Disable version reporting to skip unnecessary CF updates

---

packages/resources/src/Function.ts

Fix issue with inconsistent updates to functions

---

www/docs/constructs/App.md

Adding example for default removal policy

---

packages/resources/src/Function.ts
packages/resources/src/util/dotnetBuilder.ts
packages/resources/src/util/pythonBuilder.ts

Function: Python functions in different stacks cannot share the same srcPath

---

packages/cli/test/nodejs-build-bundle-nodemodules/lib/index.js
packages/cli/test/nodejs-build-bundle-nodemodules/nodejs-build-bundle-nodemodules.test.js
packages/cli/test/nodejs-build-bundle-nodemodules/src/lambda2.js
packages/resources/src/util/nodeBuilder.ts

Function: do not reinstall bundle nodeModules

---

packages/resources/src/Api.ts
packages/resources/test/Api.test.ts

Api: support route throttling

---

packages/cli/scripts/deploy.js
packages/cli/scripts/start.js
packages/cli/scripts/util/cdkHelpers.js
packages/cli/test/helpers/run-start-command.js
packages/cli/test/start-base/start-base.test.js

sst start: fix --outputs-file option not working

---

packages/resources/src/Auth.ts
packages/resources/test/Auth.test.ts

Auth: add cognitoIdentityPoolId property

---

packages/resources/src/Api.ts
packages/resources/src/util/apiGatewayV2AccessLog.ts
packages/resources/test/Api.test.ts
packages/resources/test/WebSocketApi.test.ts

Closes #742 
Created a canary release for this one.  Once it's confirmed working well I'll write docs for it

Api: Support passing stages

---

.eslintrc.json
README.md
packages/cli/assets/cdk-wrapper/run.js
packages/cli/scripts/start.js
packages/cli/test/playground/lib/index.ts
packages/cli/test/playground/lib/script-stack.ts
packages/cli/test/playground/src/script.js
packages/resources/src/Api.ts
packages/resources/src/App.ts
packages/resources/src/Function.ts
packages/resources/src/Script.ts
packages/resources/src/Script/cfn-response.ts
packages/resources/src/Script/index.ts
packages/resources/src/Script/outbound.ts
packages/resources/src/Script/util.ts
packages/resources/src/index.ts
packages/resources/test/Script.test.ts
www/docs/constructs/Script.md
www/sidebars.js

Script: construct for running scripts during deployment

---

packages/resources/src/Function.ts

Function: Remove readonly for exported types

---

packages/core/src/update/update.ts

CLI: Clear cache when updating package version

---

packages/resources/src/App.ts
packages/resources/src/Function.ts
packages/resources/src/Stack.ts
packages/resources/test/Function.test.ts
packages/static-site-env/test/sst-env-outputs-not-found/sst-env-outputs-not-found.test.js
www/docs/constructs/App.md
www/docs/constructs/Stack.md

Function: New api for default props

---

packages/resources/src/StaticSite.ts

When `sst start` is run, a placeholder static site is used. Depending on their particular use case or workflow, some users may not want this behavior, and want the static site to deploy like normally.
This resolves issue #817

StaticSitic: Add 'disablePlaceholder' boolean to StaticSite props

---

www/docs/constructs/ReactStaticSite.md

Just noticed a minor typo in this document.

Fix typo in ReactStaticSite.md

---

packages/resources/assets/NextjsSite/custom-resource/s3-handler.py
packages/resources/assets/StaticSite/custom-resource/index.py

StaticSite: Extended boto3 client timeout

---

packages/cli/bin/scripts.js
packages/core/src/state/state.ts

Trim stage input to avoid empty stage names

---

packages/create-serverless-stack/templates/csharp/test/%stack-name.PascalCased%.test.template.js
packages/create-serverless-stack/templates/fsharp/test/%stack-name.PascalCased%.test.template.js
packages/create-serverless-stack/templates/go/test/%stack-name.PascalCased%.test.template.js
packages/create-serverless-stack/templates/javascript/test/%stack-name.PascalCased%.test.template.js
packages/create-serverless-stack/templates/python/test/%stack-name.PascalCased%.test.template.js
packages/create-serverless-stack/templates/typescript/test/%stack-name.PascalCased%.test.template.ts

I found this when I created the ts template. I don't check another language but I think this fix seems right.

fix wrong path in template

---

packages/cli/bin/scripts.js
packages/core/src/update/update.ts

SST Update: Allow specifying version + do not require stage name

---

www/docs/constructs/App.md
www/docs/constructs/Stack.md
www/docs/monitoring-your-app-in-prod.md

Update docs for addDefaultFunctionLayers

---

www/docs/faq.md

Add missing word on why SST chose to use esbuild

Docs: Update faq.md

---

packages/resources/src/util/nodeBuilder.ts

Function: Minify nodejs bundle

---

packages/resources/src/Table.ts
packages/resources/test/Table.test.ts
www/docs/constructs/Table.md

Table: implements addGlobalIndexes and addLocalIndexes

---

packages/cli/assets/debug-stack/lib/DebugStack.js

No automated testing yet.
Fixes #883

sst start: set log retention in debug stack - #883

---

packages/resources/assets/StaticSite/stub/index.html

Tweaking copy for static site placeholder site

---

www/docs/monitoring-your-app-in-prod.md

Fixing steps for Epsagon in docs

---

packages/cli/package.json
yarn.lock

Fix for breakpoints causing disconnects

---

packages/resources/assets/stub/index.js

Fix extra certs issue

---

packages/cli/test/playground/lib/eventbus-stack.ts
packages/cli/test/playground/lib/index.ts
packages/resources/src/EventBus.ts
packages/resources/test/EventBus.test.ts

EventBus: fix event bus cannot be imported by name

---

packages/cli/scripts/util/ConstructsState.js
packages/cli/test/playground/lib/api-stack.ts
packages/cli/test/playground/package.json

Console: incorrect route path in Api panel for custom stage

---

packages/resources/src/Table.ts
packages/resources/test/Table.test.ts

Table: add instructions for importing tables with stream enabled

---

packages/core/src/index.js

Core: after a deploy failure, redeploy detects no changes

---

packages/cli/scripts/util/cdkHelpers.js
packages/core/src/index.js

Fix sst deploy fail with error "Cannot convert undefined or null to object

---

packages/core/src/index.js

sst deploy: UPDATE_FAILED shown instead of the actual error message

---

packages/cli/bin/scripts.js
packages/core/src/index.js
www/docs/packages/cli.md

sst start: default CloudFormation rollback behavior to true

---

packages/resources/src/StaticSite.ts

Make deployId public

---

www/docs/environment-variables.md

Just a typo in the documentation. :-)

Docs: Add a missing new line in code sample

---

packages/resources/src/App.ts
packages/resources/src/Stack.ts
packages/resources/test/Function.test.ts
www/docs/constructs/App.md
www/docs/constructs/Stack.md

Function: allow setDefaultFunctionProps before Functions are created

---

packages/resources/src/util/permission.ts
packages/resources/test/Function.test.ts
www/docs/util/Permissions.md

Function: allow imported IConstructs in attachPermissions

---

packages/cli/scripts/start.js

Fix crash when function not found

---

packages/cli/assets/debug-stack/lib/DebugStack.js

Block public access for DebugStack S3 bucket

---

packages/core/src/cli/StacksBuilder.ts

Cli: sst start fails when using custom stackName

---

packages/cli/scripts/start.js

Initialize ws server after runtime server

---

packages/core/src/runtime/server.ts

Cli: disable xray tracing for local invocation

---

packages/cli/test/playground/lib/api-stack.ts
packages/cli/test/playground/lib/index.ts
packages/core/src/index.ts

Cli: detect exports still in use and temporarily add to template

---

packages/cli/scripts/start.js

Cli: fix build error when folder path contain spaces

---

packages/resources/src/Function.ts

Function: add support for Python 3.9

---

packages/resources/bin/copy-rds-migrator.js
packages/resources/src/util/apiGatewayV2AccessLog.ts
packages/resources/test/Api.test.ts
www/docs/constructs/Api.md
www/docs/constructs/WebSocketApi.md

Requests:
- Garret Harp https://serverless-stack.slack.com/archives/C01JG3B20RY/p1644110856017439?thread_ts=1644103081.206979&cid=C01JG3B20RY

Api: access log retention takes RetentionDays format

---

www/docs/advanced/monitoring.md

This updates the [Monitoring documentation](https://docs.serverless-stack.com/advanced/monitoring) to include instructions for configuring New Relic logging and telemetry on Lambda functions.

Add monitoring instructions for New Relic

---

packages/resources/src/Auth.ts

Requests:
- Ash https://serverless-stack.slack.com/archives/C01JG3B20RY/p1644292081824339

Auth: add custom email and sms sender triggers

---

packages/static-site-env/README.md
packages/static-site-env/bin/scripts.js
www/docs/frontend.md
www/docs/packages/static-site-env.md

sst-env: add support for SST app directory lookup

---

packages/resources/src/ApiGatewayV1Api.ts
packages/resources/test/ApiGatewayV1Api.test.ts

ApiGatewayV1Api: cannot set restApiName

---

packages/resources/src/Construct.ts
packages/resources/src/DebugApp.ts

Check for instanceof DebugStack is not reliable inside DebugApp

---

packages/cli/test/playground/lib/api-stack.ts
packages/resources/src/Auth.ts
packages/resources/test/Auth.test.ts
www/docs/constructs/Auth.md

Auth: import existing UserPool

---

packages/console/src/App/Stage/RDS/index.tsx
packages/console/src/data/aws/rds.ts

RDS: fixed 0 showing as <null>

---

packages/cli/scripts/start.js

sst start: show descriptive message for "Unable to find function"

---

packages/cli/scripts/start.js
packages/cli/test/playground/lib/api-stack.ts

sst start: show descriptive error message when remote Lambda timed out

---

packages/resources/src/DebugStack.ts
www/docs/constructs/DebugStack.md

Allow overriding s3 bucket and function props in debug stack

---

packages/cli/scripts/start.js
packages/core/src/runtime/ws.ts

sst start: fix large payload IllegalLocationConstraintException error in new regions

---

www/docs/auth.md

Typo in auth.md

---

packages/core/src/runtime/server.ts
packages/core/src/runtime/shells/bootstrap.py

Requests:
- Seth https://serverless-stack.slack.com/archives/C01JVDJQU2C/p1646095076032089?thread_ts=1645824438.487029&cid=C01JVDJQU2C

sst start: add Lambda contexts required by Lambda power tool logger

---

packages/cli/scripts/start.js

it had to do with this
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0a2f0c574ce4fa573ef4e85f8c98f90c2fdf683a/types/node/readline.d.ts#L372

fix ctrl-c twice issue

---

packages/core/src/runtime/handler/node.ts

Requests:
- Jan https://serverless-stack.slack.com/archives/C01JG3B20RY/p1646124788116099

Function: do not set esbuild "external" without "bundle" is disabled

---

examples/rest-api-mongodb/package.json
examples/rest-api-mongodb/src/package.json
examples/rest-api-mongodb/stacks/MyStack.js

Fix lambda transpiling issue in mongodb example

---

packages/console/src/App/Stage/Buckets/Detail.tsx

fixed showing the loading sign while creating new folder

---

packages/console/src/App/Stage/Buckets/Detail.tsx

S3: copy signed url of object instead of s3 url

---

packages/console/src/App/Stage/Dynamo/index.tsx

Console: fix dynamoDB copy

---

packages/cli/test/playground/lib/index.ts
packages/cli/test/playground/lib/table-stack.ts
packages/console/src/App/Stage/Functions/index.tsx

Added kinesis streams in functions tab

---

packages/resources/src/App.ts
packages/resources/src/FunctionalStack.ts
packages/resources/src/index.ts
packages/resources/test/FunctionalStack.test.ts

Functional Stacks

---

examples/rest-api-postgresql/cdk.context.json
examples/rest-api-postgresql/package.json
examples/rest-api-postgresql/src/lambda.js
examples/rest-api-postgresql/src/migrations/first.js
examples/rest-api-postgresql/stacks/MyStack.js
examples/rest-api-postgresql/stacks/index.js

Update Postgres example using RDS construct

---

packages/console/src/App/Stage/Panel.tsx
packages/console/src/components/Tooltip.tsx

Added Tooltips to icons in sidepanel

---

packages/cli/scripts/deploy.js
packages/cli/scripts/start.js

Cli: support absolute paths for --outputs-file

---

packages/core/src/cli/StacksBuilder.ts

Fixes:
https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1648499780594159?thread_ts=1648485783.353319&cid=C01HQQVC8TH

Fix infinite rebuild loop (backport)

---

packages/core/src/cli/StacksBuilder.ts

Fixes:
https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1648499780594159?thread_ts=1648485783.353319&cid=C01HQQVC8TH

Fix infinite rebuild loop

---

packages/console/src/App/Stage/Functions/Detail.tsx
packages/resources/src/Function.ts

Function: Add architecture prop

---

packages/cli/test/playground/lib/app-sync-api-stack.ts
packages/console/src/App/Stage/GraphQL/index.tsx
packages/resources/src/AppSyncApi.ts
packages/resources/src/util/appSyncApiDomain.ts
packages/resources/test/AppSyncApi.test.ts
www/docs/constructs/v1/Api.snippets.md
www/docs/constructs/v1/AppSyncApi.snippets.md

AppSyncApi: support custom domain

---

packages/core/src/index.ts

Cli: handle CDKToolkit bootstrap stack stuck in REVIEW_IN_PROGRESS

---

packages/resources/src/AppSyncApi.ts
packages/resources/test/AppSyncApi.test.ts

Requests:
- Ravi https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1650710786314029

AppSyncApi: support NONE data source

---

packages/core/src/runtime/shells/bootstrap.py

Try to do something informative when the handler returns something that is not JSON serializable. Previous behavior resulted in bootstrap.py crashing, leading to a timeout in the client.
Another option would be to just serialize the unserializable part to something that is easy to recognize such as `<unserializable bla bla bla...>`, but it felt more explicit to throw an error.

Handle JSON encoding errors in bootstrap.py

---

.changeset/cyan-geese-decide.md
packages/resources/src/WebSocketApi.ts
packages/resources/test/WebSocketApi.test.ts

WebSocketApi: add getRoute() to make WebSocketRoute accessible

---

.changeset/eighty-needles-raise.md
packages/resources/src/Table.ts
packages/resources/test/Table.test.ts

Table: lift timeToLiveAttribute to top level

---

.changeset/sixty-timers-walk.md
packages/cli/bin/scripts.mjs
packages/core/src/state/index.ts

Cli: check for invalid stages names

---

.changeset/late-mugs-retire.md
packages/resources/src/util/apiGatewayV2Domain.ts
packages/resources/test/Api.test.ts

Api: allow external imported domain names

---

.changeset/smart-timers-lay.md
packages/resources/src/NextjsSite.ts
packages/resources/test/NextjsSite.test.ts

NextjsSite: support after deploy command hooks

---

.changeset/eleven-cars-beam.md
packages/cli/scripts/start.mjs
packages/core/src/cli/KyselyTypeGenerator.ts
packages/core/src/cli/PothosBuilder.ts
packages/core/src/cli/StacksBuilder.ts

sst start: update static-site-environment-output-keys.json on redeploy

---

www/docs/constructs/EventBus.md

Just fixing some copy-pasta or old docs copy mistake

docs: updated copy in EventBus docs

---

www/docs/advanced/testing.md

I had to dive through the examples to find the new syntax, hope this helps!

Update docs to reflect v1 testing syntax

---

.changeset/mighty-numbers-jump.md
packages/resources/src/nextjs-site/custom-resource/edge-lambda.ts

NextjsSite: fix updating function timeout fail to deploy

---

.changeset/sharp-months-watch.md
packages/resources/src/Api.ts
packages/resources/test/Api.test.ts
www/docs/constructs/Api.about.md

Api: support Lambda container routes

---

packages/resources/src/Config.ts

Doc: https://www.typescriptlang.org/docs/handbook/2/objects.html

Interface elements should end with ; not ,

---

www/docs/learn/domain-driven-design.md

Fix: Grammar Typo

---

.changeset/early-sloths-heal.md
packages/core/assets/bootstrap/cdk-app/bin/index.mjs
packages/core/src/bootstrap/index.ts

Bootstrap: encode tags in base64 to pass to bootstrap stack

---

.changeset/new-mails-cheer.md
packages/resources/src/util/apiGatewayV2Cors.ts
packages/resources/test/Api.test.ts

Api: fix removing cors options causes error

---

.changeset/eighty-buses-laugh.md
packages/resources/src/Table.ts
packages/resources/test/Table.test.ts
www/docs/constructs/Table.about.md

Table: support event filtering for stream consumer

---

packages/resources/assets/RemixSite/server-lambda/regional-server.js

RemixSite: Fix malformed cookie header

---

.changeset/great-schools-taste.md
packages/resources/src/Function.ts
packages/resources/test/Function.test.ts

Function: do not use layers when live debugging

---

.changeset/wicked-birds-boil.md
packages/resources/src/Bucket.ts
packages/resources/test/Bucket.test.ts
www/docs/advanced/importing-resources.md

Bucket: support notifications on imported S3 Buckets

---

packages/resources/src/AppSyncApi.ts
www/docs/constructs/App.tsdoc.md
www/docs/constructs/AppSyncApi.tsdoc.md
www/docs/constructs/Bucket.tsdoc.md
www/docs/constructs/NextjsSite.tsdoc.md
www/docs/constructs/RemixSite.tsdoc.md
www/docs/constructs/StaticSite.tsdoc.md
www/docs/constructs/ViteStaticSite.tsdoc.md

Fix the AppSyncApiNoneDataSourceProp code example.
Not sure if the change applied in the correct file/way because of the:
_!! This file has been automatically generated, do not edit  !!_
comment at the beginning of the file.

AppSync: Fix None DataSource code example

---

.changeset/five-turkeys-rush.md
packages/resources/src/Job.ts
packages/resources/test/Job.test.ts

Job: fix environment not added

---

packages/resources/src/Bucket.ts
www/docs/constructs/Bucket.tsdoc.md

https://github.com/serverless-stack/sst/issues/2087

update bucket attach permissions to notification doc

---

packages/resources/src/Bucket.ts

Fix typo in src/Bucket.ts

---

.changeset/little-peas-camp.md
packages/resources/assets/BaseSite/custom-resource/s3-upload.py

StaticSite: handle Gatsby build's 404.html folder

---

www/docs/upgrade-guide.md

Typo in Update upgrade-guide.md

---

www/docs/editor-integration.md

chore: fix typo

---

.changeset/chatty-dryers-play.md
packages/sst/src/constructs/ApiGatewayV1Api.ts

Cognito: handle multiple userPoolIds for authorizer

---

.changeset/curvy-rivers-try.md
packages/sst/src/constructs/Api.ts
packages/sst/test/constructs/Api.test.ts
www/docs/constructs/Api.about.md

Api: support NLB route type

---

www/docs/upgrade-guide.md

the construct for bucket in exmaples has some incorrect bracketing

typo: incorrect bracketing

---

.changeset/new-tomatoes-press.md
packages/sst/src/constructs/Auth.ts
packages/sst/src/constructs/EdgeFunction.ts
packages/sst/src/constructs/SsrFunction.ts
packages/sst/src/constructs/SsrSite.ts
packages/sst/src/constructs/StaticSite.ts

SsrSite: fix circular dependency on deploy

---

.changeset/rare-avocados-fry.md
packages/sst/src/cli/commands/secrets/set.ts
packages/sst/src/stacks/app-metadata.ts
packages/sst/src/stacks/metadata.ts

Fix `stream/consumer` not available in Node.js 14

---

.changeset/silent-pans-talk.md
packages/sst/src/constructs/RDS.ts

Fixes: https://github.com/serverless-stack/sst/issues/2505

RDS: Fix migrator function handler path

---

www/docs/advanced/iam-credentials.md

Switched out `--role-arn` to `--role`

correct docs - updated iam-credentials.md

---

.changeset/cyan-bears-beg.md
packages/sst/src/constructs/Api.ts
packages/sst/src/constructs/cdk/HttpAwsIntegration.ts
packages/sst/test/constructs/Api.test.ts
pnpm-lock.yaml
www/docs/constructs/Api.about.md
www/docs/constructs/Api.tsdoc.md
www/package.json

Api: support AWS proxy route type

---

packages/create-sst/bin/presets/examples/layer-chrome-aws-lambda/templates/stacks/ExampleStack.ts

@jayair updated!
https://github.com/serverless-stack/sst/pull/2651

Update to use `external`

---

.changeset/gorgeous-seas-nail.md
packages/sst/src/bootstrap.ts

Lambda runtime has no nodejs.18x in China partition

---

www/docs/advanced/importing-resources.md

Update the configuration to make it work as an example. Solves https://github.com/serverless-stack/sst/issues/2695

Update advanced confiugraiton

---

www/docs/advanced/monitoring.md

Also adding some comments and more explanation.

Fixing the New Relic docs with code that will work in SST2

---

.changeset/quiet-tools-buy.md
packages/sst/src/iot.ts
www/docs/live-lambda-development.md

Reduce IOT message chunk size to fix Live Lambda bug

---

.changeset/blue-actors-give.md
packages/solid-start-sst/index.d.ts
packages/solid-start-sst/package.json

Add type definitions to the package to resolve LSP warnings

Add types for solid-start-sst

---

CONTRIBUTING.md

Suggesting some changes in CONTRIBUTING.md
Mainly don't use anymore `yarn` but `pnpm`.
Thanks 😇

doc: edit CONTRIBUTING.md

---

.changeset/tasty-ducks-whisper.md
packages/sst/src/node/future/auth/adapter/microsoft.ts
packages/sst/src/node/future/auth/index.ts

Microsoft Adapter added for future/auth construct

Future Auth: Added Microsoft

---

.changeset/early-ladybugs-add.md
packages/sst/src/node/future/auth/adapter/spotify.ts
packages/sst/src/node/future/auth/index.ts

Added Spotify Adapter to future auth to make it easier to use

feat(future-auth): Added SpotifyAdapter

---

examples/api-sst-auth-google/README.md
packages/create-sst/bin/presets/examples/api-sst-auth-google/templates/README.md

Fix broken link in examples/api-sst-auth-google/README.md

Fix broken link in example

---

.changeset/tasty-plants-move.md
packages/create-sst/bin/create-sst.mjs

I think it fixes #3011 
I wasn't able to confirm the fix, I am not sure how to run it locally so couldn't verify the fix.
Is there any docs on the dev setup and building the `sst` command and running it locally?
Thanks.

`Continue` -> `Return`

---

examples/bucket-image-resize/.vscode/launch.json
examples/bucket-image-resize/package.json
examples/bucket-image-resize/packages/functions/src/resize.ts
examples/bucket-image-resize/pnpm-lock.yaml
pnpm-lock.yaml

Update example Bucket image resizes with latest AWS SDK version 3.

[Examples]: Update bucket image resize with latest aws sdk

---

www/docs/constructs/StaticSite.about.md

I spent quite some time debugging the issue to find this in the SST Discord by [Darko](https://discord.com/channels/983865673656705025/1098339579779616860/1102733007267307601) and might help people in the future.
If this information should not be added or is better suited to a different document, please feel free to close the PR or suggest an alternative.

Docs: Added note about Vite environment convention

---

www/docs/learn/create-a-new-project.md

* Add Multi-Package commands
* Use SST CLI for Dev Lambdas

Learn: Create a New Project

---

www/docs/learn/start-the-frontend.md

* Added Multi-packager
* Updated version on vite output example

Learn: Start the Frontend

---

www/docs/learn/write-to-the-database.md

* Added Multi-packager
* Added link to SST Console

Learn: Write to the Database

---

www/docs/learn/make-updates.md

Updated language for the changes to the GraphQL query using ChatGPT-4.

Learn: Make Updates

---

www/docs/learn/deploy-to-prod.md

* Update commands to avoid npx.
* Grammar Updates.

Learn: Deploy to Prod

---

.changeset/old-files-listen.md
packages/sst/src/runtime/handlers/rust.ts

Modify the build command based on the user’s function configuration.

Add arm64 support for the Rust runtime

---

.changeset/thin-boxes-shave.md
packages/sst/src/constructs/Table.ts
packages/sst/test/constructs/Table.test.ts

fix: prevent overwriting FilterCriteria in Table consumers (#3115)

---

.changeset/friendly-bobcats-thank.md
packages/sst/src/credentials.ts

Respect project region for AWS credentials provider

---

www/docs/constructs/AstroSite.about.md
www/docs/constructs/RemixSite.about.md
www/docs/constructs/SolidStartSite.about.md
www/docs/constructs/SvelteKitSite.about.md
www/docs/constructs/v1/RemixSite.about.md

Doc: fix examples on protecting SSR sites behind API Gateway

---

.changeset/stale-eagles-rhyme.md
packages/sst/src/constructs/SsrSite.ts

Fixes https://github.com/sst/sst/issues/3213.

Add copyFiles to RemixSite cdk server

---

www/docs/constructs/NextjsSite.about.md

`SubnetType.PRIVATE_WITH_NAT` is deprecated.

docs(NextjsSite): update subnet type

---

www/docs/config.md

[Discord conversation](https://discord.com/channels/983865673656705025/1153484863593263144)

docs: mention Config.secret is not free to use

---

www/docs/constructs/StaticSite.about.md

doc: Update StaticSite.about.md

---

packages/sst/src/cli/commands/dev.tsx

Solves [Issue-3358](https://github.com/sst/sst/issues/3358)

sst: Removes the wtf console log when devving

---

.changeset/chilled-kiwis-stare.md
packages/sst/src/constructs/SsrFunction.ts

Moves props destructure to allow sane defaults with overrides.
Resolves #3369

bug: Fixes SSR Function props

---

www/docs/going-to-production.md

The current suggested config for the programmatic app deploy with Github actions isn't working. I added my config with some extra configurations that fixed my own problems, and should also help more users.

Docs: Fixing Github Workflow deploy config

---

.changeset/forty-goats-trade.md
packages/sst/src/constructs/NextjsSite.ts

NextjsSite: fix edge import order

---

.changeset/rare-seas-flow.md
packages/sst/src/node/job/index.ts

Job: fix job type shows "never"

---

www/docs/constructs/Function.about.md

Added some important details needed to deploy some Python code as a Function.

Added some more details on creating a Python Lambda handler.

---

.changeset/moody-buttons-retire.md
packages/sst/src/constructs/RDS.ts
packages/sst/test/constructs/RDS.test.ts

Raised a PR to add support for MySQL8.0
https://discord.com/channels/983865673656705025/1170442962178691092

 Allow support for MySQL v8.0

---

www/docs/constructs/Service.about.md

A couple docs changes based on some rough edges I ran into while getting up and running with SST.

Docs: Updates to Service docs

---

.changeset/heavy-colts-reply.md
packages/sst/src/node/future/auth/adapter/apple.ts

fix: cjs being thrown in to provider

---

www/docs/constructs/index.md

Small edit to the intro sentence wording.

Documentation tweak for grammar/wording on https://docs.sst.dev/constructs

---

www/docs/advanced/importing-resources.md

according to https://docs.sst.dev/constructs/Topic#importing-an-existing-topic

docs: Update to the new way of importing an existing SNS Topic

---

packages/sst/src/cli/commands/secrets/list.ts

[sst/cli]: Fix hang on empty secrets list

---

.changeset/plenty-bugs-notice.md
packages/sst/src/runtime/handlers/dotnet.ts

PR for issue: https://github.com/sst/sst/issues/3418

logs errors to stdout

---

.changeset/hungry-otters-behave.md
packages/sst/src/cli/commands/secrets/list.ts

Closes: https://github.com/sst/sst/issues/3789

fix: wrap output in single quotes to allow for multi-line secrets

---

.changeset/dry-boats-pay.md
packages/sst/src/node/future/auth/index.ts
packages/sst/src/node/future/auth/proxy.ts
packages/sst/src/node/future/auth/session.ts

Dereference old auth from future auth

---

packages/sst/src/constructs/Service.ts

AWS allows a maximum of 20 Cache Policies per account. This limit is hit quickly if every service generates its own cache policy. We need a way to reuse cache policies across multiple services.
Something similar was done for Nextjs sites here: https://github.com/sst/sst/issues/899

[Service] Allow reuse of cache policies for Service constructs

---

.changeset/loud-queens-whisper.md
packages/sst/src/node/auth/adapter/link.ts

by using an optional parameter on `LinkConfig` interface

enhancement: make magic link expiry configurable

---

packages/sst/src/constructs/SsrFunction.ts
pnpm-lock.yaml

Fixes https://github.com/sst/sst/issues/3858

Fix streaming + warming causing internal handler to lose access to context object
