packages/cli/scripts/util/cdkHelpers.js
Fixes the issue where npm/yarn doesn't flatten the plugin dependencies if another package in the user's app has conflicting versions. In these cases, ESLint cannot find the plugins or parsers.
=> Forcing ESLint to look at own node_modules to resolve plugins

packages/resources/lambda/stub/index.js
The stub lambda keeps trying to reconnect to web socket when the debug stack is removed. This prints out a lot of logs and cost $ for CloudWatch Logs.
=> Stub Lambda should not reconnect to websocket on error code 1006 ENOTFOUND

packages/resources/src/Function.ts
Add NodeJS 14 Runtime to list of valid runtimes. Close #86
=> Support nodejs14.x Lambda runtime

packages/cli/bin/scripts.js, packages/cli/scripts/deploy.js, www/docs/packages/cli.md
Add support for writing AWS CloudFormation output to a JSON file with the outputs-file flag on sst deploy.
Closes #94
=> Support --outputs-file option for `sst deploy`

packages/cli/scripts/start.js, packages/cli/scripts/util/cdkHelpers.js, packages/resources/src/Function.ts, packages/resources/src/util/builder.ts
Previously, the target was set to `es2015` — #115. But for some ES syntax, esbuild doesn't transpile down to `es2015` — #136.
Fixes #136 by:
- Setting the CDK and Lambda (`sst start`) target to the current Node version
- And Lambda bundle target to the function runtime that's used
=> Set the esbuild target based on the current NodeJS runtime or Lambda runtime

www/docs/constructs/Function.md
Provided examples of setting a Dead Letter Queue (#231)  and passing SSM parameters into Lambdas as environment variables (#209).
=> Adding examples to Function construct documentation

packages/resources/src/util/permission.ts, packages/resources/test/Function.test.ts, www/docs/constructs/Function.md
This is one way to add support for issue #256. 
This change would make it possible to give Functions permissions to invoke other Functions:
```js
const sns = new sns.Topic(this, "Topic");
const table = new sst.Table(this, "Table");
const moreFun =  new sst.Function(this, "MyLambda", {
handler: "src/myLambda.main"
});
fun.attachPermissions([sns, table, moreFun]);
```
=> Support attaching Function invoke permissions

www/docs/constructs/Function.md
Adds an additional line to the documentation in the Function construct to point the reader to App for the setting of default function properties
=> Function doc line to reference default func props

www/docs/migrating-from-serverless-framework.md
A while back I asked the following question:
What is the  SST equivalent of the following command to be able to mock the SST API :
```
$ serverless invoke local --function get --path mocks/get-event.json
```
In my PR I just added a section on how to go about.
=> SST equivalent of a SLS local invocation

www/docs/constructs/StaticSite.md
Under the "Configure the internally created CDK Bucket instance" section the dynamdbTable property appears to be a typo and should be s3Bucket.
=> Replace dynamodbTable property with s3Bucket

packages/resources/src/AppSyncApi.ts
close #417
Creating a resolver from a data source results in the inability to update that resolver data source later. 
https://github.com/aws/aws-cdk/pull/12973 was merged to revert allowing resolvers to be created against the API.
This change creates the resolver from the AppSync graphqlApi API which allows you to update the resolver in place.
=> AppSyncApi: create resolver from the api not datasource

www/docs/constructs/StaticSite.md
Looks like the property tableName is supposed to be bucketName.
=> StaticSite: update typo tableName to bucketName

www/docs/deploying-your-app.md
Fixing a small typo I found on the `deploying-your-app` page.
=> docs(deploying-your-app) Fix small typo

packages/resources/src/Function.ts, packages/resources/src/util/goBuilder.ts, packages/resources/src/util/nodeBuilder.ts, packages/resources/src/util/python/bundling.ts, packages/resources/src/util/pythonBuilder.ts, packages/resources/test/Function.test.ts
Fixes #635 
I started to write a test but wasn't sure if there was a recommended way to check what's in `./build` for the specific handler
=> Support copyFiles regardless of runtime

packages/resources/src/Queue.ts, packages/resources/test/Queue.test.ts
I decided not to override a name that the user configured so that nothing unexpected happens
fixes #639
=> Queue: Append .fifo to queue name when fifo is true

packages/resources/src/StaticSite.ts, packages/resources/test/StaticSite.test.ts
Seems the linter made a few extra formatting changes.  The core change is in `lookupHostedZone`.
Fixes #614
=> Honor a hostedZone construct if given as props

packages/resources/src/Function.ts
The Go build returns an absolute path while the Node build returns a relative one
This structure could use a bit of refactoring since it wasn't intended to support multiple language from the beginning. Will follow up with that
=> Fix for copyFiles because outCode does not reliably return relative path

packages/resources/src/Function.ts, packages/resources/test/Function.test.ts
=> Function: Throw useful error when copyFiles target does not exist

packages/resources/src/Function.ts, packages/resources/test/Function.test.ts
=> Function: infer copyFiles destination from source path

packages/resources/src/StaticSite.ts, packages/resources/test/StaticSite.test.ts, www/docs/constructs/ReactStaticSite.md, www/docs/constructs/StaticSite.md
Enhancement.  As discussed on Slack. With documentation , a new test case,  and two test cases updated.  I've tested this e2e for my own hostname.
In brief, for external domains omit customDomain, and include:
```
cfDistribution: {
domainNames: ["www.domain.com"],
certificate: Certificate.fromCertificateArn(this, "MyCert", certArn)
}
```
Then set external domain's CNAME record to the cloudfront distribution's URL.
=> StaticSite: Add support for external domains

packages/resources/src/App.ts, packages/resources/test/App.test.ts, www/docs/constructs/App.md
=> App: Support setting defaultRemovalPolicy

packages/core/src/packager/packager.ts
Without this change, hitting the root drive (whatever letter) would case a RangeError: Maximum call stack size exceeded
=> Making Windows compatible

packages/resources/src/Api.ts, packages/resources/test/Api.test.ts
This PR adds the public property `httpApiArn` to `sst.API` so that it can be referenced as needed.
Format is `arn:partition:apigateway:region::/apis/api-id`
Closes issue #805 
See Slack thread for more context:  https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1631258358391400
=> Add ARN property to API stack

packages/cli/scripts/test.js
We lost the ability to load variables from .env.test on this commit: https://github.com/serverless-stack/serverless-stack/commit/7976a797776478ea8a1049086d474e3f61e4d010
This pull request restores the ability to load .env.test variables.
=> Correctly load .env.test variables when running tests.

packages/resources/src/util/nodeBuilder.ts
When providing custom esbuild config options, namely `plugins`, the path provided is a relative path. During the course of the esbuild delegation, the path is modified to an absolute path. The problem is when compiling for multiple functions, the app path will get prefixed each time, resulting in a non-existent absolute path.
As an example:
```
Building Lambda function src/lambda/graphql.main
Before: config/esbuild.js
After: /Users/tylerflint/Code/tylerflint/serverless-app-template/config/esbuild.js
Building Lambda function src/lambda/web.main
Before: /Users/tylerflint/Code/tylerflint/serverless-app-template/config/esbuild.js
After: /Users/tylerflint/Code/tylerflint/serverless-app-template/Users/tylerflint/Code/tylerflint/serverless-app-template/config/esbuild.js
```
The solution is …
=> Ensure esbuild config is deep copied

packages/cli/scripts/util/cdkHelpers.js
This PR is a follow-up to #885. Another instance where the custom config object needs to be deep cloned to protect against side affects with multiple function compilations.
=> Ensure customConfig is deep cloned to avoid side affects

www/docs/monitoring-your-app-in-prod.md
Multiple links to Epsagon docs linked to 404 pages.
I tried to select the correct links in the current documentation based on context clues and the originally linked URL
=> [Documentation] Update links to Epsagon docs

packages/create-serverless-stack/templates/typescript/package.template.json
Since the nodejs runtime for TypeScript template is now 14, it would be beneficial and even in some cases saving from bugs to add @types/node as dev dependency with the latest version for major being 14.
Because often the type definitions for node is installed without specifying version, and in that case the latest is installed, and usually it is recommended to match the major version with the node version and types.
=> Add type definitions for Node and ensure that the major version is the same with default runtime

packages/resources/src/util/permission.ts
When an invalid grant is trying to be permitted to a resource, the process will error out trying to call `undefined`, which will result in this error:
```bash
TypeError: construct[methodName] is not a function
```
And it might not be clear to the user why exactly the error is thrown. So I guess it is better to check if the provided grant exists on the construct and is a function, and only then call it, otherwise throw error explaining that a relevant method should exist on the grant.
Example:
=> Throw if the permission grant does not exist on the construct

packages/resources/src/Function.ts
Small fix that moves the `tracing` option to its relevant JSDOC counterpart.
=> Fix: Move the tracing option to under its relevant JSDOC

packages/resources/src/Script.ts
I want to create a Script subclass that uses NodejsFunction.
=> Script create user function protected

examples/rest-api-ts/tsconfig.json
The `lib` directory does not exist most probably it has been renamed to `stacks`
=> Update include property into ts.config

www/docusaurus.config.js
Now we'll get something like this _(without author's name)_:
so we can easily see if the docs has been updated since the last time :)
I didn't tested this locally, but I've followed this guide: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs
=> Display last update time on docs

packages/resources/src/util/apiGatewayV2Domain.ts, packages/resources/test/Api.test.ts, packages/resources/test/WebSocketApi.test.ts, www/docs/constructs/Api.md, www/docs/constructs/StaticSite.md, www/docs/constructs/WebSocketApi.md
Added support for adding custom domains to the `Api` construct that are outside of Route 53. 
Sample code example:
```ts
const api = new sst.Api(this, "Api", {
customDomain: {
domainName: "api.sst.sh",
isExternalDomain: true,
certificate: acm.Certificate.fromCertificateArn(
this,
"Certificate",
"arn:aws:acm:us-east-1:000639264671:certificate/xxxx"
),
},
routes: {
"GET /": "src/lambda.main",
},
});
```
=> added external custom domain support to Api construct

packages/cli/assets/debug-stack/lib/DebugStack.js, packages/resources/src/Stack.ts
Fixes #1048: Added "never" deploy condition to SSTMetadata cloudformation resource to bypass Unknown Resource error when deploying stack to GovCloud.
Fixes #1049: Replace explicit partition in ARN of API Gateway in DebugStack with dynamic partition to enable Live Lambda Development on GovCloud.
=> Add support for AWS GovCloud

packages/static-site-env/package.json
Adding @serverless-stack/static-site-env to a project will result in more than 450 dependencies being installed in node_modules.
```
{
"name": "test",
"version": "0.1.0",
"private": true,
"devDependencies": {
"@serverless-stack/static-site-env": "0.61.2"
}
}
```
This is due to a dependency on @serverless-stack/core from which no functionality is actually used. This PR removes the @serverless-stack/core dependency and a few others and replacing them with the dependencies that are actually required by the script itself. This will keep the number of transitive dependencies to a bare minimum.
=> static-site-env: remove unused and add missing dependencies

packages/cli/scripts/util/createJestConfig.js
In a test I'm using a library that uses Axios, this _should_ be fine... but
somehow I get an error indicating that a `OPTIONS` request gets a 405 error. This is curious, as this library should not do a OPTIONS request. After viewing the stacktrace, it became apparent that jsdom had stubbed the nodejs-native request functionality, tricking Axios in using that. This is insane, that in a SST app jsdom is loaded (a React utility).
So this PR sets the testEnvironment to `node` to prevent loading jsdom.
=> Prevent loading jsdom, which mocks fetch/XHR

packages/core/src/runtime/shells/bootstrap.py
This prevents crashing the live dev lambda handler. Fixes the issue discussed in Slack: https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645525472903309
=> sst start: add trace to Python bootstrap.py error reporting

www/docs/auth.md
This PR fixes a typo in the Auth documentation: `resoruces` -> `resources`.
=> Auth: Fix documentation typo

packages/cli/bin/scripts.js, packages/core/package.json, packages/core/src/aws-sdk/awscli-compatible.ts, packages/core/src/aws-sdk/index.ts, www/docs/packages/cli.md, yarn.lock
Mirrors the CDK's changes in https://github.com/aws/aws-cdk/pull/19454 to support SSO.
While I was in this section, added missing support for the `--profile` parameter.
There was a lot of whitespace changes that I think kicked in because of prettier/linting. Relevant changes (aside from CLI) exactly mirror the pull request linked above.
Closes https://github.com/serverless-stack/serverless-stack/issues/1552;
=> CLI: add support for SSO and --profile option

packages/cli/scripts/start.js, packages/cli/scripts/util/cdkHelpers.js
Resolves https://github.com/serverless-stack/serverless-stack/issues/1565
This change updates the search for matching stack outputs to be based on the stack id rather than name which should be stable (?)
=> sst-env: fix cannot find environment when custom stack names are used

packages/resources/src/FunctionalStack.ts
Adds a small change to bind `this` in `stack` usage allowing idiomatic `new Resource(this, 'Id', {})` usage of CDK resources.
(example stolen from graphql)
```typescript
import { App, Stack, StackContext, RDS } from "@serverless-stack/resources";
export default async function main(app: App) {
app.setDefaultFunctionProps({
runtime: "nodejs14.x",
srcPath: "backend",
environment: {
SSM_PREFIX: `/${app.name}/${app.stage}/`,
SSM_FALLBACK: `/${app.name}/fallback/`,
},
});
if (app.local) app.setDefaultRemovalPolicy(RemovalPolicy.DESTROY);
app
.stack(Database);
}
export function Database(this: Stack, ctx: StackContext) {
const cluster = new RDS(this, "RDS", {
engine: "postgresql10.14",
defaultDatabaseName: "starter",
migrations: "./migrations",
});
return cluster;
}
```
=> enhancement: allow `this` in `stack`

.gitignore, packages/console/src/data/aws/dynamodb.ts
Currently using special column names like `_type` does not work in the console, this PR should fix that.
=> Use ExpressionAttributeNames instead of the key directly

packages/console/src/App/Stage/Stacks/index.tsx
Hey, saw this random bracket on the bottom left of the console stack page, which looks like it's from a typo
=> [Console]: Random bracket in Console UI

.changeset/wicked-pianos-vanish.md, examples/api-auth-lambda-authorizer-simple-response/stacks/MyStack.ts, packages/create-sst/bin/presets/examples/api-auth-lambda-authorizer-simple-response/templates/stacks/MyStack.ts
Add `responseTypes: ['simple']` which was missing to the `api-auth-lambda-authorizer-simple-response` example
=> Fix simple lambda authorizer example

.changeset/young-deers-eat.md, packages/resources/src/ApiGatewayV1Api.ts, packages/resources/src/util/apiGatewayV2Domain.ts, packages/resources/test/Api.test.ts, packages/resources/test/ApiGatewayV1Api.test.ts
Use the sst.Api customDomain.cdk.hostedZone property when the customDomain.hostedZone is not set
Refer to https://github.com/serverless-stack/serverless-stack/issues/1771
=> Allow custom CDK hostedZone for sst.Api customDomain

.changeset/smart-peaches-check.md, packages/core/src/runtime/handler/go.ts
To support real Zero-Config for golang on M1 Mac  these environment variables have to be set. Otherwise go will use the current systems architecture which is ARM instead of AMD64 on an M1 Mac.
Currently there is only one supported golang runtime (go1.x) which only has amd64 Processors. But after #1271 there will be the possibility to use ARM runtimes. So #1271 should change this to include logic based on real architecture. Not needed for now.
This fixes issue #1757
=> bug: golang configuration needed on M1 Mac

packages/console/src/data/aws/dynamodb.ts
Relates to [this thread](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1653026414646839)
A scan with filters in the Console DynamoDB view do not succeed because the `KeyConditionExpression` keys are not prefixed with `#`
=> console: fix dynamodb scan KeyConditionExpression

www/docs/advanced/tagging-resources.md
AWS CDK v2 consolidates the stable parts of the AWS Construct Library, including the core library, into a single package, aws-cdk-lib. https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
=> Docs: Migrating Tags to AWS CDK v2

examples/remix-app/README.md, examples/remix-app/web/package.json
```sh
yarn create sst --template examples/remix-app
```
Would fail to fetch node modules from `web` workspace because it was missing a name in the workspace scope, and a version.
Some readme updates to remove svelte references.
=> Examples: Remix app workspace corrections

www/docs/constructs/Cron.md
As far as I can tell, it should be `enabled: !app.local` if you want to "[d]isable the cron job from automatically running while developing" ? Otherwise it's only enabled if running locally.
=> Update Cron construct documentation

packages/resources/src/Table.ts
Change the example documentation for `localIndexes` to use `localIndexes` instead of `globalIndexes`.
=> Fix typo in example documentation

README.md
They are no longer shipped with SST as of [v1](https://docs.sst.dev/constructs/v0/migration#eslint-changelog).
=> Removed irrelevant note on Jest and ESLint

packages/resources/src/Function.ts
[If the stack is in `us-east-1`, a "normal" `lambda.Function` can be used instead of an `EdgeFunction`](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-cloudfront-readme.html#lambdaedge).
However, the SST Function construct sets some environment variables, which [are not supported @ edge](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html#lambda-at-edge-runtime-restrictions).
Enabling the `removeInEdge` option for these environment variables solves the problem
=> Function: allow using @ edge

.changeset/neat-queens-judge.md, packages/resources/src/Stack.ts
=> Stack: use root.account instead of CDK_DEFAULT_ACCOUNT environment variable

www/docs/constructs/Queue.about.md
There are two imports of `Queue` that happens and the docs made it seem like it should both be coming from the main AWS CDK instead of separating the imports.
=> docs: updated queue docs to specify the cdk queue vs sst queue

www/docs/advanced/testing.md, www/docs/environment-variables.md, www/docs/packages/node.md
The docs specified that the generated SSM names are prefixed with `/aws/`, while in fact the generated names are prefixed with `/sst/`.
https://github.com/serverless-stack/sst/blob/0bc3ef4cd10977c13ec3856742a75133d0e6722f/packages/core/src/function-config/index.ts#L142-L144
https://github.com/serverless-stack/sst/blob/0bc3ef4cd10977c13ec3856742a75133d0e6722f/packages/core/src/function-config/index.ts#L150-L152
Also fixed some typos.
=> Docs: Parameter and Secret SSM name

www/docs/auth.md
This code snippet is the first time you see `useSession` used and there's no mention up to this point where that import comes from. The first time I went through this I had to search the repo for `useSession` to find it. Although it's now mentioned lower in the page, having the import there will ensure copy to clipboard has everything you need for a quick paste  without having to scroll further and/or search the repo.
=> Add useSession import to clarify Auth docs

.changeset/new-pugs-dream.md, packages/cli2/src/stacks/build.ts, packages/core/src/runtime/handler/node.ts, packages/core/src/stacks/build.ts, packages/resources/support/bridge/build.mjs, packages/resources/support/custom-resources/build.mjs
I'm having an issue with a ".zip" corrupted file being uploaded to S3. It comes from a "\n" being placed on the output file:
https://github.com/serverless-stack/sst/blob/6f72f3c11c03abb4163941efd2c0a718741a33d8/packages/resources/support/custom-resources/build.mjs#L12-L15
Related issue: #2069
=> Replace "\n" by ";" on custom-resoruces build.

examples/api-oauth-github/stacks/MyStack.ts
https in localhost causes redirect errors on logout.
=> changed https to http in localhost

.changeset/curly-rules-impress.md, packages/resources/assets/RemixSite/server-lambda/polyfill.js, packages/resources/src/RemixSite.ts
This PR enables treeshaking of ESBuild whilst also ensuring that the required Remix polyfills do not get removed during the treeshake. Results in smaller bundle sizes that still work when deployed.
Remix by default opts into treeshaking via the `"sideEffects": false` config in `package.json`. Users can opt out per their needs still.
Tested and verified against a deployed application.
=> fix: RemixSite polyfilling with treeshaking enabled

.changeset/dry-dingos-search.md, packages/core/src/cli/PothosBuilder.ts, packages/resources/src/Api.ts
Pothos schema wouldn't be built if using the new 1.18 "graphql" route type.
=> Build pothos schema if route type is "graphql"

packages/console/src/App/Stage/Api/index.tsx, packages/console/src/App/Stage/Functions/Detail.tsx
This enables CMD + Enter to submit the form on the API or Function pages in the sst console (Ctrl + Enter for Windows).
I've tested this locally and confirmed it passes in the correct query params, headers, and body for API.
Issue: https://github.com/serverless-stack/sst/issues/2276
=> console: Enable CMD/Ctrl + Enter to submit form

packages/sst/src/node/api/index.ts, www/docs/clients/api.md
Note: Same as #2279 but this time for the sst2 branch
There was an existing `usePath` but it returned an array of path segments (split on `/`). If you define your route like this:
```typescript
{
'POST /user/{id}': 'function/user/update.handler',
}
```
Then `id` will be present in `event.pathParameters`. In this case you could also get the id with:
```
const path = usePath();
const id = path[1];
```
But it's much nicer to use the 'named' path param by getting it from `event.pathParameters`. Especially if you are trying to re-use code where the `id` might not always be in the same position in the path.
=> Api: Adding `usePathParams`/`usePathParam` helpers [sst2]

packages/sst/src/cli/local/server.ts
Fixes issue w/ console.sst.dev failing to call the `/ping` endpoint, thus rendering the console site useless.
=> fix: enable /ping endpoint for console.sst.dev 

.changeset/young-ducks-impress.md, packages/sst/src/cli/commands/bind.ts
Usecase: There are a number of scenarios e.g. CI with Github Actions, Circle CI and others use environment variables to pass values derived during each step it the workflow. Or they define a $CI env var to define that your code/tests are running in the CI environment.
When using `sst bind 'vitest run'` or `sst bind 'playwright test'` the process.env of the parent process is not passed in full to the newly spawned test runner. Instead only the config loaded from AWS is spread and AWS_* credentials.
This change first spreads the full ENV of the parent process e.g. the CI runner to the process spawned by the bind command.
=> Update the bind command to inherit the full env of the parent process

.changeset/aggregate.mjs
It causes errors when running `npx sst update`:
```sh
% npx sst update v2.0.0-rc.32
Error: Cannot read properties of undefined (reading 'constructs')
Trace: TypeError: Cannot read properties of undefined (reading 'constructs')
at file:///Users/josh/git/USERNAME/PROJECT/node_modules/sst/cli/commands/update.js:32:54
at file:///Users/josh/git/USERNAME/PROJECT/node_modules/sst/cli/commands/update.js:36:19
at async Promise.all (index 2)
at async Object.handler (file:///Users/josh/git/USERNAME/PROJECT/node_modules/sst/cli/commands/update.js:50:5)
at process.<anonymous> (file:///Users/josh/git/USERNAME/PROJECT/node_modules/sst/cli/sst.js:40:17)
at process.emit (node:events:525:35)
at process.emit (node:domain:489:12)
at process._fatalException (node:internal/process/execution:149:25)
at …
```
=> Removing unnecessary "v" prefix on the version for the release notes

www/docs/going-to-production.md
The URLs for GHA and Travis were mixed up.
=> Fix URL typo

.changeset/metal-windows-film.md, packages/sst/src/cli/commands/plugins/pothos.ts
`sst/construct`
When using a `Api` construct with a type of `"graphql"` and you don't provide an `commands` array to the `pothos` object an error is thrown.
```
✖  Pothos: Failed to extract schema:
Cannot read properties of undefined (reading 'map')
```
example `MyStack.ts`
```typescript
import { StackContext, Api } from "sst/constructs";
export function API({ stack }: StackContext) {
const api = new Api(stack, "api", {
routes: {
"GET /": "packages/functions/src/lambda.handler",
"POST /graphql": {
type: "graphql",
function: "packages/functions/src/graphql.handler",
pothos: {
schema: "packages/functions/src/schema.ts",
output: "graphql/schema.graphql",
// commands: []
},
},
},
});
stack.addOutputs({
ApiEndpoint: api.url,
});
}
```
You can provide an empty array to `commands` to avoid this …
=> bug: sst plugin pothos throwing error when no commands array

www/docs/resource-binding.md
I believe an amendment to the "Cost" section of the resource-binding would be helpful. While AWS SSM is free to use, decrypting the secrets in AWS KMS is not free forever, the free tier has 20,000 API interactions per month and costs $0.03 per 10,000 subsequent API calls. I think this might be hit a lot sooner than many might think, I have been working on a Remix app and hit 85% of this limit with 3 secrets when developing this (lots of reloads with file saves etc). The Remix construct also does not have the api for `Config.bind` in order to cache subsequent requests with a warm lambda. This limit can probably be reduced but I believe other will incur costs in production that might otherwise not be anticipated.
=> Update resource-binding.md "Cost" documentation

packages/sst/src/pothos.ts
Allow Pothos extractSchema CallExpression to not break when schemaBuilder is still null
=> fix(pothos): Ensure CallExpression checks schemaBuilder is not null

.changeset/large-bottles-live.md, packages/sst/src/constructs/Auth.ts
If an API has a default authorizer set and the API has Auth attached, the auth routes were secured and therefor non usable.
=> Fix: Auth routes secured with default authorizer

packages/sst/src/constructs/NextjsSite.ts
npm_config_yes=true causes following error on windows:
`npm_config_yes' is not recognized as an internal or external command, operable program or batch file.`
`--yes` achieves the same thing and works cross platforms.
=> Fix: Replaced npm_config_yes=true with --yes

packages/console/package.json, packages/console/src/App/Stage/Api/index.tsx, packages/console/src/App/Stage/Functions/Detail.tsx, pnpm-lock.yaml
Enable CMD + enter for invocations. Seems like this [enhancement](https://github.com/serverless-stack/sst/pull/2298) got lost in the merge from `sst2` branch
Adds missing dependencies to console's package.json
=> console: Enable CMD+enter for invocations

.changeset/grumpy-bobcats-boil.md, packages/sst/src/constructs/SsrSite.ts
Currently the alternateNames prop has no effect when set for SsrSite construct (while it is present on many examples)
This PR is pretty basic and is just a copy paste of the code in StaticSite
While working on this I have also found that for both StaticSite and SsrSite the alternate names are only used in the cloudfront distribution settings and the additional route53 records are not created, I can either update this PR to include the code to generate the required route53 records or open a separate PR as this is kind of a different issue that affects both Static and SSR sites.
=> fix: handle alternate domain names for SsrSite construct

.changeset/curly-tigers-tell.md, packages/sst/src/runtime/handlers/python.ts
I was getting this error:
```
|  Invoked src/ ... file.lambda_handler
Error: spawn /bin/sh ENOENT
Trace: Error: spawn /bin/sh ENOENT
at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
at __node_internal_errnoException (node:internal/errors:608:12)
at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
at onErrorNT (node:internal/child_process:485:16)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
at process.<anonymous> (file:/// ... /node_modules/sst/cli/sst.js:58:17)
at process.emit (node:events:525:35)
at processEmit [as emit] (/ ... /node_modules/signal-exit/index.js:199:34)
at process._fatalException (node:internal/process/execution:149:25)
```
I fixed it by changing the current working directory of `python3`
=> Fixed hardcoded python `services` directory

.changeset/odd-beds-bake.md, packages/sst/src/stacks/deploy.ts
The CDK/CF API sends tags via multiple means. As part of resource constructs that support tags, as metadata, but also importantly as part of the API call itself.
With the v2 changes, SST is not sending tags as part of the API call breaking assumptions and controls around that API.
This restores that behavior.
=> fix: send tags with deployment call

.changeset/plenty-steaks-divide.md, packages/sst/src/runtime/handlers/python.ts
=> Python Runtime: Don't copy SST directory

packages/sst/src/constructs/Function.ts
Replaced 'nodeModules' with 'install' in NodeJSProps. Updated documentation to reflect typings.
=> Docs: replaced 'nodeModules' with 'install' in Function

.changeset/pretty-bags-crash.md, packages/sst/src/credentials.ts
Related Issue: https://github.com/serverless-stack/sst/issues/2500
Fixes MFA input running on node18:
```
Enter MFA code for arn:aws:iam::xxxxx xxxx
Error: readline was closed
Trace: Error [ERR_USE_AFTER_CLOSE]: readline was closed
at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
at new NodeError (node:internal/errors:399:5)
at Interface.question (node:internal/readline/interface:403:13)
at Interface.question (node:readline:159:5)
at prompt (file:///Users/uwilken/dev/campaign.delivery/sst/node_modules/.pnpm/sst@2.0.23/node_modules/sst/credentials.js:22:41)
at file:///Users/uwilken/dev/campaign.delivery/sst/node_modules/.pnpm/sst@2.0.23/node_modules/sst/credentials.js:28:21
```
=> fix: CLI throws error, when committing MFA on Node18

.changeset/fuzzy-terms-raise.md, packages/sst/src/project.ts
Related issue: #2397
Fix the pattern of `.env.{stageName}.local` was not read among the `.env` files listed in [Types of .env files](https://docs.sst.dev/config#types-of-env-files).
=> Project: Fix .env.<stage>.local is not loaded

.changeset/green-parrots-pretend.md, packages/sst/src/constructs/NextjsSite.ts
Issue: NextjsSite application router navigations were hard refreshing the page instead of routing in place.
Fix: router navigations now happen in-place without a full page reload.
NOTE: very small change but took a long time to figure out what was missing.
=> fix: NextjsSite allow rsc headers for in-place routing

.changeset/stale-mangos-burn.md, packages/sst/src/constructs/NextjsSite.ts
fixes #2517
`sst` 2.0.28 removed public access from the S3 bucket. But AWS doesn't allow access w/in internal lambdas w/o explicit roles.
=> fix: add s3 perms to image opt lambda

www/docs/quick-start.md
The docs currently suggest that Node 14 and npm 7 are the exact versions required, however, SST works with [Node 16 + npm 7, Node 18 + npm 8] as well.
=> Rephrase NodeJS requirements

examples/rest-services/README.md
=> Fixed typo in examples/rest-services

.changeset/modern-llamas-drive.md, packages/sst/src/bootstrap.ts, packages/sst/support/bridge/bridge.ts
From Discord: https://discord.com/channels/983865673656705025/1077267922659061882
There are currently 2 issues affecting dev mode and deployment to GovCloud as of v2.0.35:
- The bootstrap stack uses the Node 18.x runtime (not supported in GovCloud yet) despite the change in [776fb8f](https://github.com/serverless-stack/sst/commit/776fb8f269ab20c574fb7e365bffbb88d30d4a60) because `app.region` appears to be undefined at the point it is used. This PR uses `project.config.region` instead.
- The AWS IoT SDK for JavaScript has an issue that incorrectly parses IoT endpoints that contain regions with 4 segments, like `us-gov-west-1`. The workaround for this issue is to provide a region explicitly. This was done for the client side in [531310c](https://github.com/serverless-stack/sst/commit/531310c …
=> Fix dev mode in GovCloud (SSTv2)

.changeset/proud-peas-cover.md, packages/sst/src/cli/commands/plugins/kysely.ts
Fixes a bug that was causing incorrect types when using a mysql db engine.
=> Update KyselyTypeGenerator to use the correct dialect based on db engine

.changeset/nine-ghosts-leave.md, packages/sst/src/runtime/handlers/pythonBundling.ts
Discord thread: [https://discord.com/channels/983865673656705025/983866416832864350/1080155956815593532](https://discord.com/channels/983865673656705025/983866416832864350/1080155956815593532)
Docker is used to bundle Python functions since [13eb42c](https://github.com/serverless-stack/sst/commit/13eb42c041aceca3b221ae3fa60be21eea86e11a). This PR changes the way source code and dependencies are copied into the final bundle to speed up the bundling process:
- Dependencies are copied from the Docker container using `image.cp` instead of `rsync` inside the container.
- Source code is copied directly from the `entry` directory to the output directory **on the host** using `fs.cpSync` instead of `rsync` inside of the Docker container from one bind mount to another.
Here's a performance …
=> Improve Python bundling speed

www/docs/advanced/lambda-layers.md
Docs update: SST 2.0 has a new API for excluding nodejs modules from a function bundle
=> Docs: update examples for excluding Nodejs modules

packages/sst/src/cli/commands/update.ts
This avoids changing formatting of unaffected files.
Resolves: #2591
=> fix: only write package.json if changed

.changeset/twenty-cows-exist.md, packages/sst/package.json, pnpm-lock.yaml
Removing the aws-crt dependency fixes failing postinstall builds on macOS. Looks like this issue has been fixed in later versions of crt if it is needed (see: https://github.com/awslabs/aws-crt-nodejs/releases/tag/v1.15.7), but it looks like it being used transitively already from looking at the lockfile.
=> Removes `aws-crt` dependency to fix macOS install errors

.changeset/healthy-squids-thank.md, packages/sst/src/constructs/util/apiGatewayV2AccessLog.ts
=> Api: fix access log field "cognitoIdentityId" not supported in us-west-2

.changeset/loud-ears-join.md, packages/sst/src/runtime/handlers/python.ts
=> Use posix seperator when deploying python lambda

www/docs/testing.md
Minor improvement, but can help more people to avoid making mistakes like I did #2598
=> fix #2598: [docs] Wrong instructions to test API Endpoints

.changeset/three-coats-do.md, packages/sst/src/cli/commands/update.ts
This improves `sst update` to also update the version of `astro-sst` which shares the same version number as `sst` package.
=> sst/cli: sst update to also update astro-sst version

.changeset/young-ducks-deny.md, packages/sst/src/bootstrap.ts, packages/sst/src/cli/commands/bind.ts, packages/sst/src/cli/commands/env.ts
As per discussion [on discord](https://discord.com/channels/983865673656705025/1073321613589753968/1073334256765509722), I need this change in order for the env cli command to work properly on Cygwin.
Dax mentioned that he may push this himself but I haven't seen the change come in and I keep having to edit the file myself whenever I pull down new code.
=> bug: remove shell parameter from env cli

www/docs/constructs/StaticSite.about.md
Hello 👋🏼 
While reading docs I spotted that Astro is mentioned instead of static site in the `StaticSite` construct description. This PR fixes it
=> Remove mention of Astro in StaticSite construct docs

.changeset/hungry-clouds-heal.md, .changeset/pretty-ligers-compete.md, packages/sst/src/node/future/auth/handler.ts
The link on the base auth page is redirecting to port 300 instead of 3000. Missing a zero. Just fixes this. Later on maybe should be using a config instead.
=> fix: Future Auth should redirect to port 3000 instead of 300

.changeset/tall-fans-fix.md, packages/sst/src/node/future/auth/index.ts
Exported the Adapter type for future auth, so others can create their own custom adapters that satisfies the same type as required.
=> chore: exported the adapter type for future auth

.changeset/real-pets-mix.md, packages/sst/src/runtime/handlers/node.ts
Removed `process.env` being merged to local lambda.
When running lambda in `dev` mode, we should try to mimick the real AWS Lambda environment. By merging in local env variables, we give access to local variables that won't be available when deploying final code to Lambda.
The problem I encountered appeared after upgrading to v2.  I noticed, that I didn't have to give my lambda any permissions and it would still execute successfully. What I have found out, was that yes, the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` were correctly set.
But, that is when I noticed, that my lambda also had access to `AWS_PROFILE`, which was linking to my `~/.aws/credentials` file. 
- Overwrite `AWS_PROFILE` setting it to the one coming from lambda,
- State in the docs that local env variables leak to …
=> Fixed local lambda runtime having access to local env variables

.github/workflows/aws-cdk.yml
The archiver package is a aws-cdk dependency that gets converted to a dev dependency and causes sst errors. This adds it back as a dependency.
fixes #2681
=> Adds archiver package to deps for sst-cdk forked package

packages/create-sst/bin/presets/examples/api-sst-auth-facebook/templates/web/src/App.jsx, packages/create-sst/bin/presets/examples/api-sst-auth-google/templates/web/src/App.jsx
While working through auth I noticed that this was clearing with an argument. What it should actually do is remove the item that's set previously. 
You can see the docs here:
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage#examples
There's [another PR here](https://github.com/AnomalyInnovations/serverless-stack-com/pull/703) for `serverless-stack-com`
=> fix: localstorage.removeItem rather than clear

www/docs/advanced/source-maps.md
This still needs editing from someone on the team.
But also.. I just bothered to look at Sentry docs again, and check this out:
https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/esbuild/
The Sentry team really stays on top of things! That didn't exist last time I checked. I wonder if this would work with SST, though there's still the question of removing `.map` files from the SST dist folder so that they don't get bundled into the Lambda funcs.
=> Updated source map docs with details on how to upload to Sentry

www/docs/clients/site.md
Hello 👋🏼 ,
The url part of the StaticSite client docs is duplicated, it's a leftover from an old ReactStaticSite construct. It seems like it wasn't completely removed during the V2 overhaul. This PR removes the duplicated mention 😃 
Screenshot of how this looks currently:
https://docs.sst.dev/clients/site
=> fix: remove ReactStaticSite leftover

.changeset/clever-goats-jump.md, packages/sst/src/runtime/handlers/go.ts
fix "sst build", "sst deploy" and "sst dev" for GO lambdas in Win32:
- replace single-quotes with double-quotes in "go build" arguments
- escape file path separator \ in Win32
=> fix go build for Win32 #2719

.changeset/unlucky-hornets-stare.md, packages/solid-start-sst/entry-edge.mjs, packages/solid-start-sst/entry.mjs
fix(imports): update the import to reference .js
This resolves the issue discussed here: https://discord.com/channels/983865673656705025/1092771219381686312
On build the `solid-start-sst` adapter imports `solid-start/node/globals` but I assume this can not be found because of the CJS/MJS mismatch? Stack trace:
```bash
node:internal/process/promises:288
triggerUncaughtException(err, true /* fromPromise */);
^
[Error: Could not load /Users/alistairstead/code/saas/main/node_modules/.pnpm/solid-start@0.2.26_@solidjs+meta@0.28.4_@solidjs+router@0.8.2_solid-js@1.7.2_solid-start-node@0.2.26_vite@4.2.1/node_modules/solid-start/node/globals (imported by .solid/server/index.mjs): ENOENT: no such file or directory, open '/Users/alistairstead/code/saas/main/node_modules/.pnpm/solid-start@0.2.26_@solid …
```
=> fix solid start globals import

packages/sst/src/node/site/index.ts
feat(solid-start): add the missing interface to access bound resources
When using the SolidStartSite it generates the types into .sst in this interface:
```
declare module "sst/node/site" {
export interface SolidStartSiteResources {
"Adminsite": {
url: string;
}
}
}
```
However, the interface is not exposed in `sst/node/site` I have added the required const and interface definition.
=> solid start resources

packages/sst/src/cli/commands/update.ts
Update the `sst update` command to also update the `solid-start-sst` package
=> Add solid-start-sst to list of packages to update in command

.changeset/new-steaks-marry.md, packages/sst/support/python-runtime/runtime.py
Received an error related to relative imports when importing local Python modules in SST Python functions:
```log
Traceback (most recent call last):
File "/path/to/file/repo_name/node_modules/sst/support/python-runtime/runtime.py", line 97, in <module>
module = import_module(args.handler_module)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 122, in import_module
raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.testFunction'
```
Ref: https://discord.com/channels/983865673656705025/1083054101652328478
=> Add support for relative python imports

.github/workflows/aws-cdk.yml, .github/workflows/examples.yml, .github/workflows/release.yml, .github/workflows/test.yml
Removes Github actions deprecation warnings
Updated actions:
- actions/checkout
- actions/setup-node
=> Update deprecated Github actions

packages/sst/src/constructs/StaticSite.ts
Just a small typo I found while reading the API Docs!
Thank you for everything :pray:
=> Fix a small typo in API Docs

.changeset/breezy-comics-cross.md, packages/sst/src/node/graphql/index.ts
This pull request adds the ability to disable introspection in GraphQL Helix by using the disableIntrospection flag in the GraphQLHandlerConfig object. This feature allows for increased security in production environments by preventing unauthorized clients from querying the server's schema.
The following changes have been made:
1. Import the necessary dependencies: specifiedRules and NoSchemaIntrospectionCustomRule from graphql
2. Add a new optional disableIntrospection boolean property to the GraphQLHandlerConfig interface
3. In the GraphQLHandler function, set the validationRules variable based on the value of disableIntrospection
4. Pass the validationRules variable to the processRequest function
[Here](https://github.com/contra/graphql-helix/issues/50#issuecomment-922414985) is a …
=> Disable Introspection in GraphQL Helix

packages/sst/src/constructs/RDS.ts, www/docs/constructs/RDS.about.md, www/docs/constructs/v0/RDS.md, www/docs/constructs/v1/RDS.about.md, www/docs/constructs/v1/RDS.tsdoc.md, www/docs/learn/initialize-the-database.md, www/docs/learn/write-to-the-database.md
Thanks for building this tool!
Very minor change, the github page for kysely looks like it has moved from https://koskimas.github.io/kysely/ to https://kysely-org.github.io/kysely/
=> Doc: Update dead link to new location

.changeset/dry-candles-run.md, .gitignore, packages/sst/package.json, packages/sst/src/node/graphql/index.ts, pnpm-lock.yaml, www/docs/clients/graphql.md
GraphQL Helix doesn't seem to be maintained anymore. graphql-yoga is a very powerful server fully capable of running in lambdas. I've been using an implementation almost identical to this for a couple weeks now and it's been working. GraphiQL works as well.
The handler implementation is heavily based on graphql-yoga's documentation:
https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-aws-lambda
=> GraphQLHandler: replace graphql-helix with graphql-yoga

www/docs/constructs/RDS.about.md, www/docs/constructs/v0/RDS.md, www/docs/constructs/v1/RDS.about.md, www/docs/learn/index.md
Minor changes to the doc regarding Kysely links. This is an extension of this merged PR https://github.com/serverless-stack/sst/pull/2788
Some were missed while going through the docs.
=> doc: update missed kysely links

www/docs/clients/auth.md
Code snippet on auth docs page ([https://docs.sst.dev/clients/auth#usesession](https://docs.sst.dev/clients/auth#usesession)) was missing a closing quotation mark in syntax. This fixes that.
=> Auth: fix missing close quote in documentation snippet

.changeset/popular-kids-lick.md, packages/sst/src/constructs/deprecated/cross-region-helper.ts
Fixes the [issue raised on Discord channel](https://discord.com/channels/983865673656705025/1088244131429617714/1098996498810814547) when using deprecated `NextjsSite`:
```
Error occured making stack!
Error: Cannot find asset at home/mono/node_modules/support/edge-function
Trace: Error: Cannot find asset at home/mono/node_modules/support/edge-function
at new AssetStaging (home/mono/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:1402)
at new Asset (home/mono/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:736)
at AssetCode.bind (home/mono/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:4628)
at new Function (home/mono/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:7479)
at Module.getOrCreateBucket (file://home/mono/node_modules/sst/constructs/deprecated/cross-region-hel …
```
=> [construct/deprecated]: Import correctly support/edge-function for deprected NextJsSite

www/docs/advanced/customizing-ssm-parameters.md
Update `ssmPrefix` example to reflect the current behaviour https://github.com/serverless-stack/sst/commit/2f16a73daf77c800dc2b65bb2ebfe4d29a0e76fb
=> docs: Update ssmPrefix doc

packages/sst/package.json
SST package no longer points to the official repo. Introduced in #2792
=> Fix repository link in packages.json

.changeset/funny-panthers-cover.md, packages/sst/src/runtime/handlers.ts, packages/sst/src/runtime/handlers/dotnet.ts
This PR addresses the issue described in [issue2836](https://github.com/serverless-stack/sst/issues/2836), enabling the selection of .NET 6 bootstrap and ensuring the safety of input.out by utilizing quotes
=> [Fix/Dotnet]: enable the selection of dotnet6 bootstrap and secure input.out with quotes 

.changeset/chilled-jobs-march.md, .changeset/nine-dodos-heal.md, packages/sst/src/cli/commands/plugins/pothos.ts, packages/sst/src/constructs/Api.ts, packages/sst/src/pothos.ts
As mentioned by various people, for example at https://discord.com/channels/983865673656705025/983866416832864350/1080219063252435115, the Pothos extractor fails when importing "internal" packages, for example if I have an Enum type in my `core` package and import it by reference into my `functions` package (`import { MyEnum } from `@myproject/core/file`), that import will be stripped when the Pothos extractor runs.
This is my stab at a solution to this problem, by allowing the user to specify a list of package names that should be considered internal, and subsequently inlined into the schema generated by esbuild. Maybe the naming (and certainly the docstring) could be improved to better clarify the intent of the feature.
=> Allow packages to be marked as "internal" for Pothos extractor

.changeset/twenty-monkeys-drive.md, packages/sst/src/constructs/Cognito.ts, www/generate.mjs
Exposing this allows users to work with the role configuration using override: 
```js
cognito.cdk.CfnIdentityPoolRoleAttachment.addOverride("Properties.RoleMappings", {...})
```
One basic use case is users from the pool to assume a role based on the group they belong. E.g `Type: "Token"`
=> Cognito: Expose cfnIdentityPoolRoleAttachment

.changeset/weak-books-design.md, packages/sst/src/constructs/SsrSite.ts
This change resolves #2848 by specifying the Lambda Service Policy when creating the lambda function for the SsrSite server.
=> bug: Dev role defined for the function cannot be assumed by Lambda

.changeset/young-hairs-shout.md, packages/sst/src/constructs/RemixSite.ts
The previous options `serverBuildTarget` were deprecated in favor of a combination of options from the remix config, this PR deletes the deprecated ones and adds the new ones to maintain the same behavior
More info: https://remix.run/docs/en/1.16.0/pages/v2#node-cjs
=> fix(remix): delete deprecated options in favor of new supported ones

.changeset/purple-ants-march.md, packages/solid-start-sst/entry-edge.mjs
Cloudfront edge lambda headers need to be accessed via `.value`
=> Fix: header values not getting parsed in edge

packages/sst/src/constructs/SsrSite.ts
The other SSR frameworks that extend the attachPermissions method has the mention of Astro, even though they are not using Astro. See SvelteKit as example:
https://docs.sst.dev/constructs/SvelteKitSite#attachpermissions
This simply generalises to "framework" instead in the docstring
=> docs(SsrSite): generalise attachPermissions

.changeset/chilled-books-learn.md, packages/sst/src/project.ts
Aims to solve 
https://discord.com/channels/983865673656705025/1106299750636068946
Tries to avoid the situation where another sst process is spawned before another one finishes then the first one deletes the config files of the other parallel process
=> [Fix/Parallel Project Init]: Skip cleanup of very recent config files

.changeset/shaggy-panthers-vanish.md, packages/sst/package.json, packages/sst/src/runtime/handlers/java.ts, pnpm-lock.yaml
The zip-local package has dependencies with security vulnerabilities:
* https://nvd.nist.gov/vuln/detail/CVE-2022-48285
* https://nvd.nist.gov/vuln/detail/CVE-2021-43138
There is an open pull request on zip-local to fix this (https://github.com/Mostafa-Samir/zip-local/pull/18), but it's two weeks old and the maintainer has not reacted to it. Maybe it's easier to just use adm-zip instead, since it's already in the deps anyway.
I have tried to verify that it's still possible to build java functions, but my experience with Java in Lambda is nil, so I might have broken something.
=> chore: replace zip-local with adm-zip

.changeset/cold-dingos-drive.md, .changeset/fifty-ants-whisper.md, .changeset/gentle-mails-compare.md, packages/sst/src/constructs/WebSocketApi.ts, packages/sst/src/context/handler.ts, packages/sst/src/node/api/index.ts, packages/sst/src/node/auth/session.ts, packages/sst/src/node/future/auth/session.ts, packages/sst/src/node/websocket-api/index.ts, www/docs/constructs/WebSocketApi.about.md, www/docs/constructs/v1/WebSocketApi.tsdoc.md
Similar to how we have the `ApiHandler`, adding a `WebSocketApiHandler` allows access to the `useSession` and all other contexts set from the event and requestContext.
Make sure to import the hooks from the right construct as required.
```ts
import {
WebSocketApiHandler,
useHeaders,
useQueryParam,
} from 'sst/node/websocket-api'; // <-- instead of `sst/node/api`
import { useSession } from 'sst/node/future/auth';
export const handler = WebSocketApiHandler(async () => {
const session = useSession();
const headers = useHeaders();
const params = useQueryParam('hello');
console.log(session, headers, params);
return {
statusCode: 200,
};
});
```
=> feat: WebSocketApiHandler

.changeset/seven-roses-retire.md, www/docs/config.md
Following conversation on Discord, this information was only present in the upgrade guide. This PR adds it to the `Config` construct docs too.
=> Add IDE autocomplete instructions for Config construct

www/docs/packages/sst.md
The link to the AWS Profiles "cli configure files format" page has an invalid redirect on the Amazon side. It improperly encodes the hash character in the URL when attempting to link the user to the "#cli-configure-files-format" section. I've updated the link to have the correctly (un)encoded hash instead of having Amazon break the link. This is technically a bug on the Amazon side.
=> Fix AWS profiles broken link

.changeset/stupid-keys-admire.md, packages/sst/src/cli/commands/secrets/list.ts, www/docs/packages/sst.md
This PR adds `json` as a format for `sst secrets list`.
=> Add support for JSON format in secrets list

.changeset/four-llamas-talk.md, packages/sst/src/node/future/auth/adapter/google.ts, packages/sst/src/node/future/auth/adapter/microsoft.ts, packages/sst/src/node/future/auth/adapter/oauth.ts, packages/sst/src/node/future/auth/adapter/oidc.ts
This PR adds support to oidc for the `prompt` parameter in the authorisation URL.
This allows users to authenticate with an app on different accounts using the same provider.
- Discord [chat](https://discord.com/channels/983865673656705025/1109401107215687752/1109401107215687752)
- Google oidc [doc](https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters) showing prompt param
=> future/auth: add prompt support for oidc

.changeset/little-roses-beg.md, packages/sst/src/node/future/auth/adapter/google.ts, packages/sst/src/node/future/auth/adapter/oauth.ts
- Adds ability to pass through params to oauth 2.0 auth endpoints. This is needed for cases like Google where `access_type` param controls whether a refresh token is returned.
- Added Google Oauth config as only had oidc in future/auth
- Added typed `accessType` param to google config
- [Google access_type param](https://developers.google.com/identity/protocols/oauth2/web-server#offline)
- [Next auth implementation thats pretty similar](https://github.com/nextauthjs/next-auth/blob/461b52ea4f55d740b3b94de800d105a9bfc854ef/packages/next-auth/src/core/lib/oauth/authorization-url.ts#L31)
=> future/auth - forward query params to authorization endpoint

.changeset/light-zebras-double.md, packages/sst/src/cli/commands/secrets/list.ts
In some cases its been useful to know if any fallback values are being used in certain stages. For instance, making sure a prod stage isn't using any fallback values.
=> sst: Allow filtering secrets by fallback values

www/docs/long-running-jobs.md
Update the SST jobs page to make sure it's conveyed that only general1.small is included in free-tier.
One more addition could be changing [this section](https://docs.sst.dev/long-running-jobs#how-much-does-it-cost-to-use-job)
```diff
-...The general1 instance types are used.
+...The general1 instance types are used. By default SST jobs are configured to use general1.medium (7GB) instances.
```
=> Update long-running-jobs docs

www/docs/start/astro.md, www/docs/start/nextjs.md, www/docs/start/remix.md
According to used web framework, suggest where to place sst create command.
The cd command suggest to navigate to default project names, when the framework creates a new folder (astro, next, remix).
Svelte and Solid frameworks uses current directory and isn't necesary to move.
=> Suggest where to place sst create command.

packages/sst/src/constructs/Queue.ts
remove console.log from sqsQueueProps.visibilityTimeout if condition
=> remove console.log from sqsQueueProps.visibilityTimeout if condition in Queue.js

.changeset/smooth-rice-check.md, packages/sst/src/constructs/RDS.ts
https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-aurora-serverless-v1-postgresql-13
=> feature: support postgres 13.9

www/docs/configuring-sst.md
The bootstrap config option is typed in SSTConfig, but not mentioned in the docs. This PR adds bootstrap to the config options to make it easier to discover how to change the bootstrap stack name and tags.
Closes #2973
=> docs: document bootstrap config option

.changeset/many-moons-change.md, packages/sst/src/cli/commands/diff.ts
This makes it compatible with the build command. Else build builds to its own, but diff still creates the .sst/dist folder, and that does not work well within nx.
As we know have to provide arguments to build and deploy to make this work, I suggest buildDir becomes a single setting at a single spot somewhere.
=> feat: add --to argument to diff else it can only use the default buildDir

.changeset/clawsl-change.md, packages/sst/src/runtime/handlers/python.ts, packages/sst/src/runtime/handlers/pythonBundling.ts
This adds support for using the arm64 docker image to compile python dependencies and fixes the issue [described here](https://discordapp.com/channels/983865673656705025/1120466923411476512)
=> arm64 docker build support for Python functions

.changeset/angry-waves-marry.md, packages/sst/src/constructs/Bucket.ts, packages/sst/test/constructs/Bucket.test.ts
Similar to #3015 but now enforced for every bucket. This to start stopping SST buckets showing up in AWS Security Hub.
=> feat: enforce S3 https connections

examples/api-sst-auth-google/package.json, examples/api-sst-auth-google/packages/functions/src/auth.ts, examples/api-sst-auth-google/sst.config.ts, examples/api-sst-auth-google/stacks/ExampleStack.ts
- Correct use of ViteStaticSite
- Correct name of auth.handler
- Import SSTConfig as type 
- Update aws-cdk-lib and constructs
=> Fix examples/api-sst-auth-google

.changeset/nasty-rules-wash.md, packages/sst/src/constructs/RDS.ts, packages/sst/test/constructs/RDS.test.ts
It's often a requirement in enterprise environments that secrets must be encrypted with a custom key, and not use the AWS default key in your environment. The reason is that destroying of the stack means all data encrypted with that key is also no longer accessible (if AWS really destroys the key).
This also means I had to fix which credentials were accepted: you can now also change the default root user of your cluster, another enterprise requirement.
=> feat: allow a secret to be encrypted with a custom KMS key

.changeset/thin-coats-approve.md, packages/create-sst/bin/presets/other/java/templates/sst.config.ts, packages/sst/src/constructs/Function.ts, www/docs/constructs/Function.about.md
This is similar to #2870 but that PR is a bit obsolete as it included a no longer necessary update to the CDK version.
We need Java17 as this is the out of the box supported version of CodeBuild for the STANDARD_7_0 image. And the version that supports node 18. So if you want to mix both (we do), you need Java 17.
=> feat: support java17 as runtime option

.changeset/silver-fishes-draw.md, packages/sst/src/constructs/SsrSite.ts
fixes: #3042
The initial PR only fixed the unversioned files.
=> fix: add s3 key prefix to versioned sub dir

.changeset/dirty-bugs-hug.md, packages/sst/src/constructs/RDS.ts, www/docs/constructs/v0/RDS.md, www/docs/constructs/v1/RDS.tsdoc.md
`postgresql10.14` has been deprecated by aws and therefore when building with this engine an exception occurs:
`Db dbCluster/Cluster AWS::RDS::DBCluster CREATE_FAILED Resource handler returned message: "The engine mode serverless you requested is currently unavailable. (Service: Rds, Status Code: 400, Request ID: x)" (RequestToken: x, HandlerErrorCode: InvalidRequest)`
- [link to discord discussion](https://discord.com/channels/983865673656705025/1121721945516429344/1121721945516429344)
- [Link to aws announcement](https://repost.aws/questions/QU0ligxMlJSJWhzzgKbKgytQ/questions/QU0ligxMlJSJWhzzgKbKgytQ/announcement-amazon-aurora-postgresql-10-x-end-of-support-is-january-31-2023)
=> Remove deprecated rds engine

www/docs/constructs/Stack.about.md, www/docs/constructs/v1/Stack.about.md
fixes typo on the word `async`
=> Fix: typo on docs

.changeset/dull-papayas-laugh.md, .changeset/polite-dogs-beg.md, packages/sst/src/constructs/NextjsSite.ts, packages/sst/src/constructs/SsrSite.ts
The SsrSite distribution for static files in `/public` was creating a new S3Origin for each item.
=> fix: remove duplicate S3 origins for static assets

.changeset/ten-socks-build.md, packages/sst/src/runtime/handlers/node.ts
It seems there is a missing await for fs.writeFile
This causes issues on our runners:
Error: Failed to build function ".build/handler.main"
Error: Command failed: npm install
npm ERR! code EJSONPARSE
npm ERR! path /home/ubuntu/actions-runner/_work/project-name/project-name/.sst/artifacts/c8f5e1b156ab358204912997ac001c6caa658f1734/package.json
npm ERR! JSON.parse Unexpected end of JSON input while parsing empty string
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.
The issue happens truly randomly, but in most cases it fails. After failing execution we can see valid json in package.json file.
=> SST / NodeJS runtime: await for fs.writeFile

www/docs/learn/initialize-the-database.md
* Added multi-package example for the future gen command with a bit of rewording to make the flow make sense with the command pulled into the multi-package code display.
* Updated a couple of conjunctions.
* Put last step in the behind the scenes info into the list with the rest of the steps.
Note: I believe it may be necessary to add instructions to restart `sst dev` after the database is initialized.  I received an error related to  "graphql-query-batcher" when I tried to start the front end, which was resolved after I restarted sst dev.  I didn't exhaustively test my hypothesis, in the hopes that you would just know the answer, but I can if needed :)
=> Learn: Initialize the Database

.changeset/dirty-grapes-knock.md, packages/sst/src/constructs/util/permission.ts, packages/sst/test/constructs/RDS.test.ts
This is related to #3035. If you use migrations, the migration function should also be able to decrypt the key.
BTW, this permissions thing looks very complex, instead of `secret.grantRead()` it becomes a whole different ball game.
=> fix: grant migration function permission to decrypt custom secret encryption key

.changeset/polite-parents-chew.md, packages/sst/src/constructs/RemixSite.ts
I've found that occasionally, the "copyFileSync" calls fail in CI because the build directory does not exist. I've made a slight change to create it if it doesn't.
=> fix: ensure build directory exists when building RemixSite

.changeset/chatty-carpets-pull.md, packages/sst/src/runtime/handlers/rust.ts
If a build in Rust fails there is no other way to debug. This makes debugging of the issues very hard!
=> Output build errors in Rust runtime

.changeset/fluffy-birds-switch.md, packages/sst/src/constructs/BaseSite.ts, packages/sst/src/constructs/SsrSite.ts, packages/sst/src/constructs/StaticSite.ts, packages/sst/test/constructs/RemixSite.test.ts
Adding `fileOptions` to `SsrSite` will allow users to customize cache control and content type headers for static assets, much like `StaticSite`.
Discussion:
https://discord.com/channels/983865673656705025/1124926722740080651/1124926722740080651
=> feat: added fileOptions to SsrSite

packages/console/src/App/Stage/Dynamo/index.tsx
DyanmoDB sets are currently rendered as an empty object `{}` in the console. I've added a replacer function to convert them to an array before stringifying. 
Note: this only addresses rendering sets in the table view. The DynamoDB editor is a whole different story since converting it to an array there would change the data type to a DynamoDB List after saving.
=> console: fix rendering sets in DynamoDB table view.

.changeset/swift-monkeys-sin.md, packages/sst/package.json, pnpm-lock.yaml
This version bump fixes https://github.com/evanw/esbuild/issues/3219 which we are seeing when trying to build and deploy our Remix site via SST + seed.run
=> Bump esbuild version

.changeset/clawsl-change.md, packages/sst/src/cli/telemetry/post-payload.ts
Handles ECONNREFUSED for telemetry as discussed here[here](https://discord.com/channels/983865673656705025/1132050168821325845/1132099003413168248)
=> Bugfix/handle telemetry DNS error

packages/sst/src/credentials.ts
"Bare" imports that don't name what they are importing are never elided by Typescript and end up in the compiled JS. That doesn't make any sense for this package since it only has types.
I don't know why this was originally added, but it still typechecks without it now so I don't think it's necessary.
Partial fix for #3140
=> Delete side effect only @aws-sdk/types import

.changeset/modern-buckets-switch.md, packages/sst/src/constructs/Function.ts
Currently the Function construct, when live debugging, uploads to bootstrap bucket instead of using IoT if the payload is above 3MB. The policy statement, however, for the function only allows `s3:*` for the **bucket**, but not the **objects** within. This PR adds the additional wildcard resource for the objects contained within the bucket.
Note: It may be prudent to implement a more specific resource such as `<arn>/pointers/*` instead of the broad wildcard I have used here, but I will leave that up to your discretion.
Relevant lines in `iot.ts` where this PutObjectCommand is currently failing:
https://github.com/serverless-stack/sst/blob/b56c2ea021290211c72841c605cec58579ef3591/packages/sst/src/iot.ts#L49-L58
=> Function: Add policy statement resource for Function to access bootstrap bucket objects during live debugging.

.changeset/ten-pandas-smash.md, packages/sst/src/constructs/NextjsSite.ts
As of next 13.4.13+, Nextjs has added `next-url` to the vary headers. https://github.com/vercel/next.js/blob/canary/packages/next/src/client/components/app-router-headers.ts#L10
=> fix: add next-url to NextjsSite header

packages/astro-sst/README.md, packages/astro-sst/package.json, packages/astro-sst/src/lambda/entrypoint.ts, packages/astro-sst/src/lambda/index.d.ts, packages/astro-sst/src/lambda/transform.ts, packages/sst/src/constructs/AstroSite.ts, packages/sst/src/constructs/SsrSite.ts, pnpm-lock.yaml
This PR adds support for Astro's [streaming feature](https://docs.astro.build/en/guides/server-side-rendering/#streaming) when deployed with the `astro-sst/lambda` adapter. I've tested this against the current app I'm working on and verified that I can defer component loading with these changes.
Example app:
https://github.com/adamelmore/astro-streaming-example
[With streaming (this PR)](https://d35a996kza03bv.cloudfront.net/):
https://github.com/serverless-stack/sst/assets/2363879/cb6985ac-7598-4a07-8bf9-0157cd845f7c
[Without streaming](https://dq1bgzm27fqgl.cloudfront.net/):
https://github.com/serverless-stack/sst/assets/2363879/571cc20c-c95d-46ba-a46d-8731007f293f
=> feat: astro streaming

.changeset/unlucky-files-count.md, packages/sst/src/constructs/NextjsSite.ts
I forgot to set `next-url` for edge mode. Refactored duplicate methods to reduce similar mistakes.
=> fix: refactor duplicate code; set next-url for edge

www/docs/constructs/AppSyncApi.about.md
As discussed in the help topic in Discord: https://discordapp.com/channels/983865673656705025/1131711866129874964
Just adding a small snippet to the end of the doc to cover how you overcome N+1 fetching problems using `BatchInvoke`-configured resolver/handlers.
=> Adding docs to overcome GraphQL N+1 problem with AppSyncApi.

.changeset/warm-pants-crash.md, packages/sst/src/runtime/handlers/node.ts
https://discord.com/channels/983865673656705025/1136428086531997797
Deadlock errors occurring again during build since this change https://github.com/serverless-stack/sst/commit/ba2156ff74b8a8e3d48ea243f17a743c2b134502 now means ctx is no longer stored in cache when running in deploy mode, and so is not cleaned up properly on exit.
=> fix: dispose of esbuild context when in deploy mode

.changeset/three-gifts-jam.md, packages/sst/src/node/event-bus/index.ts
This PR makes the EventHandler helper pass attempts count further to the callback. It's set on the event in the retrier logic.
Per Discord topic: https://discord.com/channels/983865673656705025/1132162244973699146 
I'm also not 100% sure about the changesets stuff, feel free to let me know if something is off 😃
=> EventBus: pass attempts count to EventHandler callback

.changeset/thin-cheetahs-sit.md, packages/sst/src/cli/commands/update.ts
RE: https://discord.com/channels/983865673656705025/1007139657324187729/1135930483851673673
Just a small change to respect the newline chars when overwriting `package.json`s during `sst update` - works when there is a newline and when there isn't one
=> fix: respect newline char when writing package.json

.changeset/early-cameras-leave.md, packages/sst/src/runtime/handlers/java.ts
Currently a gradle build job is started for every Function even if it points to the same directory, causing massive machine load and build errors.
This could still start two builds, but only in succession. Ideally there's some mop up logic in the parent so it starts builds only once. But this is probably good enough for most scenarios.
Instead of `gradlew` ideally I would have the ability to run a `gradle:build` or so if one is defined in `package.json`. The idea here is to make sure gradle does not write output to the project directory, as that is annoying in monorepo projects. So would need to specify `--project-output-path` I believe.
But that might be another PR, this already greatly improves our builds.
=> feat: run only one gradle build per java directory

www/docs/constructs/Service.about.md
Small issue with the Service docs related to the Dockerfile:
Need to be in the WORKDIR where package.json is to run rpm install.
=> fix: docs for Service Dockerfile

.changeset/nice-cooks-train.md, packages/astro-sst/src/lib/event-mapper.ts
In cases where a response from Astro doesn't have a body, there's an issue where the response headers and status don't get sent to the caller. We have to call `write` before calling `end`, which I think is a quirk of the underlying runtime implementation for streaming on AWS Lambda. It doesn't appear to matter what we pass into `write`, but I stressed over it a bit (empty string was less aesthetically pleasing to me, but I don't hold a strong opinion and 0 isn't much better).
=> fix: astro redirects broken

packages/sst/package.json, pnpm-lock.yaml
This bump fixes a [bug](https://github.com/awslabs/smithy-typescript/issues/848) where the signature was sometimes incorrectly computed.
=> fix: update @smithy/signature-v4 to 2.0.4

.changeset/empty-candles-fold.md, packages/sst/src/node/service/index.ts, www/docs/clients/service.md, www/sidebars.js
This should address some [type errors](https://discord.com/channels/983865673656705025/1142284213207437453/1142284213207437453) that occur when a `Service` construct is introduced to the app
=> Service: Add node client and docs

.changeset/strong-sheep-float.md, packages/sst/support/python-runtime/Dockerfile.dependencies
Starting Aug 18 2023 the python builds which use poetry are broken.
The cause is an update in poetry used to install the dependencies. The new release uses a new version of urllib3 which requires an SSL package not available in aws python image builds used by the sst construct (aws images).
My solution is to pin the latest poetry package works (1.5.1) while AWS does not update the building images.
This is the error I get before my fix:
```
=> [internal] load .dockerignore                                                                                           0.1s
=> => transferring context: 2B                                                                                             0.0s
=> [internal] load build definition from Dockerfile.dependencies …
```
=> python-runtime: pin poetry dependency to fix ssl error

.changeset/giant-dodos-battle.md, packages/sst/src/constructs/ApiGatewayV1Api.ts
Authorizer typings seem to be incorrect in ApiGatewayV1Api
In `sst/constructs/Api.ts` the authorizer type correctly extends the `AuthorizerKeys` type to allow AuthorizerKeys to be specified as an authorizer to the function construct
https://github.com/sst/sst/blob/5fff7a6eee7309db9fd4c50e84bfb36d36f7d1e6/packages/sst/src/constructs/Api.ts#L381
```
authorizer?:
| "none"
| "iam"
| (string extends AuthorizerKeys
? Omit<AuthorizerKeys, "none" | "iam">
: AuthorizerKeys);
```
However in `sst/constructs/ApiGatewayV1Api.ts` the authorizer keys can never be assigned as a string leading to incorrect typing clashes
https://github.com/sst/sst/blob/5fff7a6eee7309db9fd4c50e84bfb36d36f7d1e6/packages/sst/src/constructs/ApiGatewayV1Api.ts#L183
```
authorizer?:
| "none"
| "iam"
| (string extends …
```
=> Fix types for api gateway v1 authorizer

www/docs/advanced/iam-credentials.md
=> Docs: Fix typo in iam-credentials.md

www/docs/custom-domains.md
Provides more detail on how to point CNAME's (for root domains) to CloudFront, as the docs currently suggest that this cannot be done.
=> Update docs on pointing CNAME's to root domains to CloudFront

.changeset/smart-oranges-change.md, packages/sst/src/constructs/Service.ts, packages/sst/test/constructs/Service.test.ts, www/docs/constructs/Service.about.md, www/generate.mjs
Added configurable health check to the target group created within the Service construct. Further to the discussion on [Discord](https://discord.com/channels/983865673656705025/991751731824308344/1146893038027817000)
The default health check created assumes that the root path of the service task returns an HTTP 200 response. When deploying 3rd party images or applying security to the service this may not be the case. If the default health check fails the deployment of the Service times out as the deployment internally for CF/Fargate does not complete. This change retains all the default configuration but enables any of the [HealthCheck](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.HealthCheck.html) props to be set. 
I considered placing this …
=> Add healthcheck props to Service construct

www/docs/going-to-production.md
You can't deploy if an existing deploy in progress, so multiple merges will cause github action sst deploy workflows to run concurrently which will fail. 
Adding a concurrency group name using the branch ref will ensure that only 1 workflow run is executed at a time for that branch, any new ones will be queued until current one is finished.
=> Add concurrency group name to workflow example

.changeset/hot-spiders-develop.md, packages/sst/src/constructs/NextjsSite.ts, packages/sst/src/constructs/RemixSite.ts, packages/sst/src/constructs/SsrSite.ts, packages/sst/test/constructs/NextjsSite.test.ts, packages/sst/test/constructs/RemixSite.test.ts, packages/sst/test/constructs/helper.ts
Fixes #3206
- Encode path to allow  having special characters in files
- Attach Cloudfront functions to all distributions
=> RemixConstruct: Encode special characters in the url path

.changeset/forty-ties-retire.md, packages/sst/src/constructs/SsrSite.ts, packages/sst/support/base-site-custom-resource/s3-upload.py
https://github.com/sst/sst/pull/3266 upgrades the remaining nodejs 14 resource functions to nodejs 16 in response to the deprecation warning from AWS. This PR does the same thing but for the Python3.7 deprecation warning
```
We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using the Python 3.7 runtime.
We are ending support for Python 3.7 in AWS Lambda. This follows Python 3.7 End-Of-Life (EOL) reached on June 27, 2023 [1].
```
The email suggests upgrading to 3.11 which I've done here -- I believe it should be backwards compatible. Also I removed some unused imports I noticed in `s3-upload.py`
=> SsrSite: Upgrade s3 handler python versions

.changeset/silly-geckos-invite.md, packages/sst/src/constructs/StaticSite.ts
This PR is similar to https://github.com/sst/sst/pull/3266 for SsrSite, except this one upgrade Python versions for [StaticSite](https://github.com/sst/sst/blob/master/packages/sst/src/constructs/StaticSite.ts#L693) construct
=> StaticSite: Upgrade S3 uploader and handler Pyhon versions 3_7 -> 3_11

.changeset/calm-suits-breathe.md, packages/astro-sst/src/lib/event-mapper.ts
The actual changes in this PR feel kind of sloppy, tbh, but these changes add compression to streamed responses. The only other issue that I should call out is it's not as efficient in terms of the compression factor as a normal, non-streamed response (because we're compressing each chunk). I think the solution to increase the compression factor would be adding some state and compressing chunks in batches, but that would add some complexity and work against the benefit of streaming in the first place.
=> feat: astro streaming compression

.changeset/clean-badgers-brush.md, packages/sst/src/node/event-bus/index.ts
Currently `createEvent` (returned by `createEventBuilder`) has an inferred return type. The return type refers to a type ` PutEventsCommandOutput ` imported from `@aws-sdk/client-eventbridge`. When a consumer of SST uses `sst/node/event-bus` and has TS config option to emit declaration files, they get a declaration file like this:
Input file:
```ts
import { createEventBuilder } from 'sst/node/event-bus';
export const event = createEventBuilder({
bus: 'bus',
});
```
Declaration file:
```ts
export declare const event: <Type extends string, Shape extends import("zod").ZodRawShape, Properties = import("zod").objectOutputType<Shape, import("zod").ZodAny, "strip">>(type: Type, properties: Shape) => {
publish: (properties: Properties) => …
```
=> node/event-bus: Fix incompatible type inference in exported function

.changeset/itchy-steaks-beam.md, packages/sst/src/constructs/AppSyncApi.ts
Resolves the warning
```
[WARNING] aws-cdk-lib.aws_appsync.GraphqlApiProps#schema is deprecated.
use apiSoure.schema instead
This API will be removed in the next major release.
```
Note: one of the tests is failing (merging array of schema files), but this is unrelated to this PR and has been failing for a a while. I was unable to fix the error so have left it.
=> Fix: Update deprecated appsync schema prop

.changeset/moody-shoes-explode.md, packages/sst/src/constructs/SsrSite.ts
Fixes this securityhub warning:
=> Enforce SSL on SSR bucket 

.changeset/six-tomatoes-rest.md, packages/sst/src/constructs/RemixSite.ts
Enforcing a `serverModuleFormat` is no longer needed now that both formats are supported.
Fixes the issue raised at  https://discord.com/channels/983865673656705025/1072426878431940758/1152175369823211573
=> Fix RemixSite enforcing ESM

www/docs/advanced/monitoring.md
I'd like to add [Baselime](https://baselime.io) to the list of monitoring providers.
=> Add Baselime to the monitoring docs

packages/sst/src/node/future/auth/session.ts
For some reason AWS does not lowercase header names in Websocket events, so the `useSession` utility does not work.
There's also this PR from a while ago mentioned in a comment in the same file that would fix this issue in a possibly better way https://github.com/sst/sst/pull/2838/.
=> Future Auth: Fix session checking not working for websocket API's

.changeset/strange-roses-walk.md, packages/sst/src/constructs/SsrSite.ts, packages/sst/support/ssr-warmer/index.ts
SSR Warmer function was assuming a specific payload response from invoked functions and failing when response wasn't received. This PR handles these cases in a cleaner way.
PR also makes schedule of warmer configurable and reduces memory size.
Resolves #3364
=> bug: Fixes SSR warmer

.changeset/kind-moose-allow.md, packages/astro-sst/src/lib/build-meta.ts, packages/sst/src/constructs/AstroSite.ts
Removes the `astro-sst` dependency from the `sst build` process.
Resolves #3377
=> bug: Fixes Astro dependency in build

.changeset/khaki-snakes-watch.md, packages/sst/support/custom-resources/auth-keys.ts
I still need to fully test this in our project, but we get this error every time we try to remove a deployed stage:
```
2023-10-05T22:55:37.070Z	1c259060-9941-4cac-b547-7ee89d263211	INFO	[provider-framework] ThrottlingException: Rate exceeded
at throwDefaultError (file:///var/task/index.mjs:9300:24)
at file:///var/task/index.mjs:9310:39
at de_DeleteParameterCommandError (file:///var/task/index.mjs:27053:18)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async file:///var/task/index.mjs:6243:24
at async file:///var/task/index.mjs:3885:22
at async file:///var/task/index.mjs:7495:42
at async file:///var/task/index.mjs:1344:26
at async Promise.all (index 0)
at async AuthKeys (file:///var/task/index.mjs:179509:7) {
'$fault': 'client',
'$metadata': {
httpStatusCode: …
```
=> fix: replace Promise.all with PutParametersCommand

.changeset/empty-kangaroos-obey.md, packages/astro-sst/src/edge/adapter.ts, packages/astro-sst/src/lambda/adapter.ts, packages/astro-sst/src/lambda/entrypoint.ts, packages/astro-sst/src/lib/build-meta.ts, packages/astro-sst/src/lib/event-mapper.ts, packages/astro-sst/src/lib/types.d.ts, packages/sst/src/constructs/AstroSite.ts, www/docs/constructs/AstroSite.about.md
Adds ability to specify response mode (`buffer` or `stream`) and sets up environment appropriately.
- Adds `responseMode` property to `astro-sst` adapter integration function.
- Moves `serverRoutes` property to `astro-sst` adapter integration function.
- Deprecates `serverRoutes` property on `AstroSite` constructor.
Response mode should be set in the adapter integration function call in `astro.config`:
```js
import { defineConfig } from "astro/config"
import aws from "astro-sst/lambda"
export default defineConfig({
adapter: aws({
responseMode: "stream",
serverRoutes: [
"feedback", // Feedback page which requires POST method
"login",    // Login page which requires POST method
"user/*",   // Directory of user routes which are all SSR
"api/*"     // Directory of API endpoints which require …
```
=> feat: Astro SSR response modes (buffered/streamed)

.changeset/brown-ghosts-love.md, packages/sst/src/constructs/AstroSite.ts
Removes the `fileOptions` inserted by the `AstroSite` in favor of using the `SsrSite` default configuration using the S3 files as a mapping for the `fileOptions` configuration.
Resolves #3389
=> bug: Fixes Astro site cache headers

.changeset/dirty-bees-taste.md, packages/sst/src/constructs/SsrSite.ts
Adds layers as a CDK prop on the `SsrSite` construct to allow adding layers to Lambda functions.
Reference configurations:
```js
import { AstroSite } from 'sst/constructs'
import type { SSTConfig } from 'sst'
import * as lambda from 'aws-cdk-lib/aws-lambda'
const layerArn = 'arn:aws:lambda:us-west-2:764866452798:layer:chrome-aws-lambda:37'
export default {
config() {
return {
name: 'test-website',
region: 'us-west-2',
profile: 'sst'
}
},
stacks(app) {
app.stack(function Site({ stack }) {
const site = new AstroSite(stack, 'astro-site', {
cdk: {
server: {
layers: [lambda.LayerVersion.fromLayerVersionArn(stack, 'ChromeLayer', layerArn)]
}
}
})
stack.addOutputs({
url: site.customDomainUrl
})
})
}
} satisfies SSTConfig
```
=> feat: Adds layers to CDK props

.changeset/friendly-spiders-explain.md, packages/sst/src/constructs/AstroSite.ts
Fixes Astro Site error response declarations to work for both dynamic (SSR) and static (SSG) error response pages.
Resolves #3387
=> bug: Fixes Astro Site error response pages

.changeset/pretty-tips-joke.md, packages/sst/src/constructs/Function.ts, packages/sst/src/runtime/handlers/python.ts, packages/sst/src/runtime/handlers/pythonBundling.ts
This makes a couple of minor changes to SST's python build logic which help drastically speed up python builds.
In our testing, without these changes, we can build about ~240 or so node.js lambdas in 150-160s. Adding 6 python lambdas adds 40-60s to this (just for `sst build`).
After weeks of investigation, the primary culprit seems to be async vs non-async work happening, combined with the way we use both SST and python. While `runtime/handlers/python.ts`'s `build()` IS async, all of the functions it calls within `pythonBundling.ts` are synchronous. The first thing I tried was making the functions in this file also async. This causes SST to explode because `useProject()` is called before `setProject()`. I'm not sure why, but because of CDK's involvement, that would only solve part of our …
=> Options to speed up python builds

.changeset/soft-carpets-sell.md, packages/sst/src/constructs/Auth.ts, packages/sst/src/constructs/future/Auth.ts
Forgot to add this in my previous PR. Using `DeleteParameters` actually fails without these permissions.
=> fix: add delete parameters permissions to AuthKeys role

www/docs/advanced/source-maps.md
`bundle` is not a valid property on `FunctionProps` object. Instead, there's `nodejs`
=> Fix source maps documentation 

.changeset/poor-cheetahs-approve.md, packages/sst/src/constructs/Auth.ts
The docs [mention](https://docs.sst.dev/constructs/Auth#cdkid) you can provide a cdk id to the auth construct.
But doing so results in an error during `sst build`
`It looks like you may be passing in Cognito props to the Auth construct. The Auth construct was renamed to Cognito in version 1.10.0`
Seems like cdk id was added as a prop after this throw and the throw was never cleaned up.
fixes: #3479
=> Auth: Prevent throwing on CDK id

.changeset/old-pens-tell.md, packages/sst/support/custom-resources/s3-uploader.ts
The recent change to the S3 uploader script dropped support for WASM files by default. I believe adding this line in to the extensions array will address the issue.
=> Added WASM mime type to S3 uploader

.changeset/four-dingos-greet.md, packages/sst/src/constructs/AppSyncApi.ts
Currently, when using the `AppSyncApi` construct with multiple schema files, there's a few limitations due to passing each individual schema into the `buildSchema` function from `@graphql-tools/merge`.
- Sharing common types and enums etc between multiple schemas isn't possible as `buildSchema` treats each schema file separately
- `buildSchema` does not allow AppSync directives such as `@aws_iam`
Removing the call to `buildSchema` will fix both of the above limitations.
Related issues:
- https://github.com/sst/sst/issues/2104
- https://github.com/sst/sst/issues/2532
=> AppSyncApi: Improve multiple schema functionality.

.changeset/thick-flowers-try.md, packages/sst/src/constructs/App.ts, packages/sst/src/constructs/Function.ts, packages/sst/src/constructs/Job.ts, packages/sst/src/constructs/deprecated/NextjsSite.ts, www/docs/upgrade-guide.md
Solves the issue of default NodeJS being set to 16.x (causes `fetch` to fail since it was [introduced in 18.x](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental))
=> Update default NodeJS runtime to 18.x

.changeset/silent-balloons-peel.md, packages/astro-sst/src/adapter.ts
Removes the config destructuring in the Astro adapter to fix issue with MDX plugin.
=> (fix) Astro Adapter configuration override fix

.changeset/nervous-rats-invite.md, packages/sst/src/constructs/Function.ts
When multiple lambdas in a stack have sourcemaps, the order of these sourcemaps within the CF template changes between runs. This means that:
* `sst diff` will show these as changes 
* `sst deploy` will needlessly redeploy these
* `sst start` also takes longer to fully deploy its stubs
Sorting the list of sourcemaps fixes this problem. This fix can be either applied inside `constructs/Function.ts` (in `useFunctions().sourcemaps.forStack()`) or `constructs/App.ts` (during the creation of the SourcemapUploader CustomResource). It seems cleaner to me to fix it in Function.ts, so this is the approach I took.
=> Make sourcemap order in CF templates deterministic

.changeset/lazy-starfishes-lie.md, packages/sst/src/constructs/WebSocketApi.ts, packages/sst/test/constructs/WebSocketApi.test.ts
We found need for two-way communications with our WebsocketApi's, and this seems to do the trick.  CDK had the wiring already, this PR exposes it via the routes.  Example:
```typescript
const websocket = new WebSocketApi(stack, 'websocket', {
routes: {
echo: {
function: {
handler: 'server/websocket/echo.func'
},
// new:
returnResponse: true
},
}
});
```
=> WebSocketApi: Support returnResponse in route definitions

packages/sst/src/constructs/RDS.ts, www/docs/constructs/RDS.about.md, www/docs/constructs/v0/RDS.md, www/docs/constructs/v1/RDS.about.md, www/docs/constructs/v1/RDS.tsdoc.md, www/docs/learn/index.md, www/docs/learn/initialize-the-database.md, www/docs/learn/write-to-the-database.md
Noticed some links weren't taking me to the correct pages, google showed some fancy new kysely site. Lets use that.
Replace all usages of the two old kysely URLs in documentation
[1](https://kysely-org.github.io/kysely/) [2](https://koskimas.github.io/kysely/#migrations)
With the new website found at https://kysely.dev/
=> Use new kyesly website URL in docs

www/docs/constructs/NextjsSite.about.md
When we applied the config in its original form, the Next dev mode reported:
> Warning: Reverting webpack devtool to 'eval-source-map'. Changing the webpack devtool in development mode will cause severe performance regressions.
The Next.js documentation suggests to avoid changing the devtool in dev mode: https://nextjs.org/docs/messages/improper-devtool
=> sst/NextjsSite: Update NextjsSite.about.md

.changeset/wicked-moose-remember.md, packages/sst/src/constructs/RDS.ts
After following the [RDS Migration guide](https://docs.sst.dev/constructs/RDS#migrations) I ended up creating a `package.json` inside `services/migration` in order to be able to add `import { Kysely, sql } from 'kysely'` inside my migration files.
After doing so, I started seeing the following error:
```haskell
Error: EISDIR: illegal operation on a directory, read
Trace: Error: EISDIR: illegal operation on a directory, read
at Object.readSync (node:fs:751:3)
at tryReadSync (node:fs:451:20)
at Object.readFileSync (node:fs:497:19)
at file:///node_modules/.pnpm/sst@2.36.7_@types+react@18.2.39/node_modules/sst/constructs/RDS.js:367:31
at Array.map (<anonymous>)
at RDS.generateMigrationsHash (file:///node_modules/.pnpm/sst@2.36.7_@types+react@18.2.39/node_modules/sst/constructs/RDS.js:367:14) …
```
=> generateMigrationsHash should not include all files - fix EISDIR error

.changeset/cuddly-kiwis-rhyme.md, packages/sst/src/constructs/Service.ts, packages/sst/test/constructs/Service.test.ts, www/docs/constructs/Service.about.md
This PR gives users of the `Service` construct the ability to configure the Fargate task [ephemeral storage](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html).
The pulled, compressed, and the uncompressed container image for the task is stored on the ephemeral storage. I would like to use a 3rd party image that is larger than the default 20 GB ephemeral storage. 
```
CannotPullContainerError: ref pull has been retried 1 time(s): failed to extract layer sha256:7c524a8642865c29df8d3973cefe8430653ba7fea85bd386e24e522601c30227: write /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/86/fs/home/notebook-user/.local/lib/python3.10/site-packages/numpy/linalg/__pycache__/linalg.cpython-310.pyc: no space left on device: unknown
```
As a …
=> feat(service): support configuration of Fargate Task ephemeral storage

.changeset/warm-glasses-fail.md, packages/astro-sst/package.json, packages/astro-sst/src/entrypoint.ts
Update Astro dev dependency to `v4` to confirm type compatibility.
PR tested with all templates from https://github.com/bayssmekanique/astro-sst-templates to confirm deployment support and all deployed successfully.
Resolve #3555
=> chore: Update Astro to v4

.changeset/nasty-pants-beam.md, packages/sst/src/runtime/handlers/node.ts
The most recent version of `sharp` (`v0.33.0`) is not stable for cross platform/architecture deployments. Pin the version to the last stable with a note to revert once issue is corrected.
Ref: https://github.com/lovell/sharp/issues/3870, https://github.com/lovell/sharp/issues/3884, https://github.com/lovell/sharp/issues/3872
=> fix: Pin bundled `sharp` version as hotfix

.changeset/calm-olives-joke.md, packages/sst/src/project.ts, packages/sst/src/util/lazy.ts
So I noticed that when calling `initProject` twice, it seems to replace some values but not all of it.
Here's how to re-create it:
```ts
import { useProject, initProject } from 'sst/project';
await initProject({ stage: 'prod' });
const project = useProject();
console.log(project);
await initProject({ stage: 'justin' });
const project2 = useProject();
console.log(project2);
```
What I see logged out is that everything is the same between the 2 stages except for the `config.profile`. But if we deleted the `SST_STAGE` env variable before initiating the project a 2nd time, it works as expected. I think if we are passing in a config, it should take precedent before the `SST_STAGE` env variable. Either way, it's weird that the profile changes but not the stage.
My use case is: I'm writing a …
=> fix: init project doesn't replace stage

examples/api-sst-auth-facebook/stacks/ExampleStack.ts, examples/api-sst-auth-google/stacks/ExampleStack.ts, packages/create-sst/bin/presets/examples/api-sst-auth-google/templates/stacks/ExampleStack.ts
The API route for `/` and `/session` went to `.ts` rather than the name of the function which is `handler`
Also, I am not 100% sure if `"GET /": "packages/functions/src/auth.ts"` in the API Construct are needed for these examples.
=> docs: the route path was to .ts rather than the function name

.changeset/plenty-laws-pay.md, packages/sst/src/runtime/handlers/node.ts
As discussed in this [Discord thread](https://discord.com/channels/983865673656705025/1185483081621188638), many bundled dependencies like `libsql` require a platform specific binary. This PR enforces the platform specification for all `sst` built Node bundles with the passed in architecture.
This works fine for `sharp`, but it could use some testing with libraries that don't currently require binary files to ensure this does not create issues.
=> fix: enforce target args in bundler

.changeset/dry-rocks-bake.md, packages/sst/src/constructs/EdgeFunction.ts, packages/sst/src/constructs/SsrSite.ts
As discussed in this [Discord thread](https://discord.com/channels/983865673656705025/1184858611399278662), the SSR Edge deployments do not properly copy files dictated by the user as `props` on the construct (ie. `AstroSite`, `SsrSite`).
This PR ensures the `copyFile` property is passed all the way through to the function bundler, and when combined with #3588 resolves the issues noted by the reporting user in the thread.
=> fix: SSR Edge function copyfile functionality

www/docs/constructs/Cognito.about.md
when specifying a specific trigger, the method is called `attachPermissionsForTrigger`, not `attachPermissionsForTriggers`
=> Fix typo in Cognito.about.md

.changeset/honest-vans-itch.md, packages/sst/src/constructs/AstroSite.ts
This PR resolves #3601, preventing Astro route paths with very greedy RegEx values from capturing requests for static files by testing for a file extension in the CF Function and preventing rewrites if an extension is present.
Example routing before implementation of this PR:
`/fr` => `/fr/index.html`
`/sitemap-index.xml` => `/sitemap-index.xml/index.html`
Example routing after implementing this PR:
`/fr` => `/fr/index.html`
`sitema-index.xml` => `/sitemap-index.xml` (*unchanged*)
The only breaking change I can foresee with this change is if someone were to have implemented a false mime-type endpoint using the static rendering function (`/file.png` => `/file.png/index.html`) to serve an HTML page from a URL that appears to point to an asset. I can't see the value in doing this, so I'm …
=> fix: Astro greedy routes

.changeset/odd-windows-lick.md, packages/sst/support/certificate-requestor/index.mjs, packages/sst/support/custom-resources/cfn-response.ts, packages/sst/support/edge-function/cfn-response.ts, packages/sst/support/script-function/cfn-response.ts, packages/sst/support/sls-nextjs-site-function-code-replacer/lambda-code-updater.py
Ref: https://github.com/aws/aws-cdk/pull/24501
> Custom Resources need to write their response into a S3 object.
> This is implemented as a PUT request to a pre-signed URL and has to specify the `content-length` of the response object.
> Previously the CustomResource code would use `responseBody.length`.
> However this returns the number of graphemes, not bytes.
> If any utf8 characters with `graphemes != bytes` are part of the response, CloudFormation would fail the deployment with a `Response is not valid JSON` error.
=> fix: properly calculate content-length for cfn custom resource responses

www/docs/config.md
Hey I had the issue described here
https://github.com/sst/sst/issues/2904
and 
https://discord.com/channels/983865673656705025/1116777988600631457
My issue was that the `{ Config } from "sst/constructs"` is used to set Config but the `{ Config } from "sst/node/config"` is used to read the values. 
It's correct in the docs examples but easy to miss (for me anyway hah) and might be worth explicitly calling out that they are the same named export but from different locations.
This just adds a tip there.
=> docs: add note about client Config import location

.changeset/lazy-tools-float.md, packages/sst/src/constructs/Job.ts
This PR updates the docker images used for jobs, I searched the latest available ARM image with nodejs 18 and 20. 
this PR sets the new default as nodejs18 but I could revert it back to nodejs 16 if necessary so as not to create a potentially breaking change
=> Allow setting nodejs version of container image in jobs construct

www/docs/advanced/lambda-layers.md
The current example for using sharp and chrome layers uses the install option of the Function construct
This causes the function to install the package, which is not correct as we're looking to mark the function as external and use the code from the layers.
This PR converts from using nodejs.install in the function config to nodejs.esbuild.external
=> fix: Converting layer example from nodejs.install to nodejs.esbuild.external

.changeset/serious-apricots-wonder.md, packages/astro-sst/package.json, packages/astro-sst/src/entrypoint.ts
Newer versions of `astro` (`<= 4.2.0`) support including the `clientAddress` as a property of the `RenderOptions` argument for the render method. This PR grabs the `x-forwarded-for` header and uses it for the `clientAddress` with a fallback to the `remoteAddress` value (which is likely an AWS resource, not the actual user).
Resolves #2918
Astro changes that enabled the functionality: https://github.com/withastro/astro/commit/d6edc7540864cf5d294d7b881eb886a3804f6d05
=> feat: Add client address for Astro

www/docs/constructs/NextjsSite.about.md, www/docs/constructs/RemixSite.about.md, www/docs/constructs/SolidStartSite.about.md, www/docs/constructs/v1/RemixSite.about.md
Fixes some typos in the import statements of some frontend construct examples. They are as follows:
- Named import statement error on [NextjsSite quickstart](https://docs.sst.dev/constructs/NextjsSite#quick-start) step
- Named import statement error on [RemixSite quickstart](https://docs.sst.dev/constructs/NextjsSite#quick-start) step 4
- Named import statement error on [SolidStartSite quickstart](https://docs.sst.dev/constructs/NextjsSite#quick-start) step 5
- Named import statement error on [RemixSite quickstart v1](https://docs.sst.dev/constructs/v1/RemixSite#quick-start) step 4
An example:
`import { NextjsSite, StackContext } as sst from "sst/constructs";`
where as sst is incorrect.
=> docs: fix typos in frontend construct examples

.changeset/fuzzy-apes-fetch.md, packages/sst/src/runtime/handlers/rust.ts
When compiling rust lambda functions on Windows platform, there is bug when sst runtime handler for rust is trying to copy files into the artifacts folder.
Running cargo build on windows creates files with .exe extension.
Copying files into artifacts folder then failes because it cant find "main" file.
In deploy mode, there is no need to add ".exe" extension to "bootstrap" file since cargo lambda build is set up correctly to build with linux environment.
[Discord thread](https://discord.com/channels/983865673656705025/1202981470160035850)
=> Runtime: Fix rust local-lambda build step on windows #

.changeset/tame-experts-sing.md, www/docs/advanced/iam-credentials.md
These permissions are required, but not found in the docs:
`iam:PassRole` is required for deploying any stack.
`s3:GetBucketLocation` is required to use an existing CDK bootstrap bucket
=> Docs: add missing required iam roles

.changeset/fifty-rockets-protect.md, www/docs/start/remix.md
The remix starter example includes a cron job to delete uploaded files once per day, but the schedule was set to once per minute. This commits fixes the cron rate to be once per day to match the rest of the documentation.
=> Docs: Fix the cron job rate to be once a day

packages/create-sst/bin/presets/examples/prisma/templates/stacks/ExampleStack.ts
Fixed:
- update Prisma files location (remove the obsolete one - .prisma)
- rmSync and cpSync instead of removeSync and copySync
- add 'recursive' option while copying prisma files to avoid the error 'Path is a directory: cp returned EISDIR'
- remove the local only deployment to make it work with 'sst dev' mode
- load database URL from .env instead of hard coded one
- added the "linux-arm64" architecture if you are using AWS Graviton 2 (source: https://www.prisma.io/docs/orm/prisma-client/deployment/serverless/deploy-to-aws-lambda)
Some of the updates above are based on this repo: https://github.com/geauser/sst-prisma-example
Tested OK with Node 20 LTS.
=> Fix non functional template for Prisma

www/docs/constructs/SolidStartSite.about.md, www/docs/constructs/SvelteKitSite.about.md
Discovered a typo in the documentation when implementing custom domains for a SvelteKitSite. It's a hard typo to spot, search for similar typos and found the same typo in SolidStartSite.
=> Docs: Fix typo in customDomain for SvelteKitSite and SolidStartSite

.changeset/empty-chairs-taste.md, packages/sst/src/constructs/NextjsSite.ts
This PR is to bump the version of open-next to fix the recent issues in NextJS as discussed here: [500 error in console from Images](https://discord.com/channels/983865673656705025/1214865068550918215)
New version of open-next to use: **2.3.7**
=> update open-next version in NextjsSite construct

.changeset/moody-pigs-bake.md, packages/sst/src/constructs/util/astroRouteCompressor.ts
Before calling recursive tree function, check if remaining nodes have duplicate patterns and if so, only keep the first instance (since the default behavior is to accept the first matched route).
This implementation assumes that routes which cause infinite looping will have identical patterns, but that's not strictly true as the actual branching occurs when the capture groups have been removed from the pattern, so two routes could have slightly different patterns due to one having a capture and the other not. I don't foresee this ever occurring given Astro's current implementation but it's possible a plugin author could be really sloppy and write a pattern which matches but doesn't extract the slug in which case this would cause issues. If that happens, make the plugin author fix their …
=> fix[astro]: correct endless route matching loop

www/docusaurus.config.js
Fix 404 `About us` footer link.
=> docs: update `About us` footer link

.changeset/late-bottles-deny.md, packages/sst/src/constructs/AstroSite.ts
Prevents route branches that don't have a matching final node from resulting in a `null` match when a viable match exists in a lower branch.
Works best when combined with Astro's experimental `globalRoutePriority` feature ( https://github.com/withastro/astro/pull/9439) which avoids other common routing issues by prioritizing matching for plugins as well.
Resolves #3717
=> astro-fix: prevent dead-end nodes from resulting in 404

www/docs/constructs/NextjsSite.about.md
This PR addresses a critical issue in the NextjsSite construct documentation (www/docs/constructs/NextjsSite.about.md) where the basic authentication example provided did not execute as intended due to improper handling of the authorization headers and the encoding of username and password.
Encoding Improvement: The username and password are now correctly concatenated and base64 encoded outside the injection string to ensure the generated string is accurate and efficient.
Authorization Logic: Adjusted the conditional statement to directly return a 401 Unauthorized response if the authorization header does not match the expected basic auth string. This adjustment ensures a cleaner, more understandable flow of logic.
Safety Checks: Added optional chaining (?.) to the …
=> Fix configuring basic auth docs

.changeset/five-hounds-draw.md, packages/sst/src/constructs/NextjsSite.ts
- Update Open Next Version for NextJSSite construct to 2.3.8: This is to include the fix included in https://github.com/sst/open-next/pull/387
=> - Update Open Next Version for NextJSSite construct

www/docs/advanced/bootstrapping.md
I spent a long time trying to figure out how to customise the name of the CDK bootstrap stack. Turns out it's quite easy.
=> add toolkitStackName to bootstrapping docs

.changeset/chilled-laws-push.md, packages/sst/src/constructs/Service.ts, packages/sst/src/runtime/handlers/container.ts, packages/sst/test/constructs/Function.test.ts
Small fix for my earlier PR https://github.com/sst/sst/pull/3651 that added `buildSsh`, `cacheTo`, `cacheFrom` properties to Functions/containers
My `.join(",")` was in the wrong place, and was joining the characters of each string in the array instead of the array of strings which produced Docker build arguments like 
`--cache-to=type=local,d,e,s,t,=,.,,,m,o,d,e,=,m,a,x`
I updated the test I added to include additional params in the `cacheTo` object to verify things now work as expected. 
**Before**
```bash
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ …
```
=> Fix cacheTo Function/container prop

.changeset/old-camels-report.md, packages/sst/src/node/future/auth/adapter/apple.ts, packages/sst/src/node/future/auth/adapter/google.ts, pnpm-lock.yaml
Proxy the issuer calls inside Google/Apple adapters, so they are not called immediately when anything from future/auth is imported, even if these adapters are not used anywhere in the Auth code.
Using the proxy enables the two adapters to stay completely synchronous, thus posing no breaking change to the existing codebase. 
Changes were tested via package linking, and the timeouts have disappeared.
=> Fix RPError issuer timeouts with future/auth

.changeset/great-moles-lie.md, packages/sst/src/node/future/auth/adapter/apple.ts, packages/sst/src/node/future/auth/adapter/google.ts
I keep getting `config.issuer.Client is not a constructor` (for example GoogleAdapter) in SST v^2.42.0.
In the previous version it does work SST v2.41.5.
I looked into the implementation and I think this `Proxy` for resolving issuers might not be working as expected.
[Discord](https://discord.com/channels/983865673656705025/1082462837710012508/1246779198132060192)
=> fix: google and apple adapter

.changeset/sixty-snakes-admire.md, packages/sst/build.mjs
Fixes local issue when running on dotnet8.
This change should have been included in #3734.
=> Add missing dotnet8 bootstrap support copy command

.changeset/metal-spies-melt.md, packages/sst/src/node/auth/session.ts
Essentially copies the implementation of `Session.verify` from `packages/sst/src/node/future/auth/session.ts` into `packages/sst/src/node/auth/session.ts` so that users of "current `Auth`" have the ability to manually validate/verify tokens too.
Closes https://github.com/sst/sst/issues/3724
=> misc(auth): expose session.verify in non-future auth

.changeset/silly-cats-grow.md, packages/sst/src/constructs/NextjsSite.ts
Introduced in https://github.com/sst/sst/commit/96b99e08f3cfbbbdf9f25f920be73e368b0599d0
=> fix: obey runtime and memorySize configs in `NextjsSite`

.changeset/lemon-deers-eat.md, packages/sst/src/bootstrap.ts, packages/sst/src/project.ts, www/docs/configuring-sst.md
Seems weird that CDKToolkit stacks get a description by default but SSTBootstrap stacks do not. 
I have lost track of the amount of times a Devops guy has been tidying up and deleted my bootstrap stack. Would be nice to have a meaningful and customisable description to let them know not to delete it. 
CDK example below.
=> SSTBootstrap: Add description to bootstrap stack

.changeset/flat-mirrors-relax.md, packages/sst/support/python-runtime/Dockerfile, packages/sst/support/python-runtime/Dockerfile.custom, packages/sst/support/python-runtime/Dockerfile.dependencies
I've applied the fix mentioned in this [Discord comment ](https://discord.com/channels/983865673656705025/1106622583589306408/1219562915477323826) by user **jlarmst**
When monkey patching my install of `node_modeules/sst` I am able to build successfully. For transparency I don't know if this is a "good" fix, but it's the only thing that makes Python 3.12 work for me.
<details><summary>Discord Comment</summary>
<p>
I’ve searched Discord and found at least two reports of errors with python 3.12
- https://discord.com/channels/983865673656705025/1212069025937367060/1212069025937367060
- https://discord.com/channels/983865673656705025/1190123642584051733/1190123642584051733
It is most definitely failing.  Python 3.12 uses amazonlinux:2023, which has replaced `yum` with `dnf`, causing this …
=> fix: fix dockerfile build commands for python 3.12

www/docs/going-to-production.md
The default console Maximum session duration is 1h. Which will cause the ci to fail when copy pasting this code.
=> docs: update going-to-production.md

.changeset/clean-kiwis-greet.md, packages/sst/support/signing-function/helpers/queryStringToQueryParameterBag.ts
This change fixes the aws v4 signature when query string params with no values are used. This lambda is used when the option `regional.enableServerUrlIamAuth = true` is set in `SsrSite` (in my case `RemixSite`).
For example, posting to Remix index routes hits an endpoint such as:
https://xxxxx.cloudfront.net/?_data=routes%2F_index&index=
This version of the URL works as expected following the change
=> fix: query params with no values should be strings

www/docs/constructs/Function.about.md
Not sure what is the prefered way to import aws-cdk-lib according to SST but I figured it should consistent with how it's described here:
https://docs.sst.dev/constructs/Bucket#importing-an-existing-bucket
=> docs: fix IAM role code example import statements

.changeset/cuddly-pugs-bow.md, packages/sst/src/runtime/handlers/node.ts
By default NPM will install optional dependencies, even if you include --no-optional.
```
npm warn config optional Use `--omit=optional` to exclude optional dependencies, or
npm warn config `--include=optional` to include them.
npm warn config
npm warn config       Default value does install optional deps unless otherwise omitted.
```
See https://docs.npmjs.com/cli/v10/commands/npm-install#omit
=> Switch npm install command to use `--omit=optional` not `--no-optional`

.changeset/warm-carrots-yawn.md, packages/sst/src/constructs/SvelteKitSite.ts, www/docs/constructs/SvelteKitSite.about.md
Addresses: https://github.com/sst/sst/issues/2964
Taking inspiration from https://github.com/sst/sst/pull/3613 and updating the behaviours and S3 copy paths.
=> [SvelteKitSite construct] add basePath support into SvelteKitSite construct
